// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc_rtc_msgs.proto
// Protobuf C++ Version: 6.32.0-rc2

#ifndef mc_5frtc_5fmsgs_2eproto_2epb_2eh
#define mc_5frtc_5fmsgs_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#  error "Protobuf C++ gencode is built with an incompatible version of"
#  error "Protobuf C++ headers/runtime. See"
#  error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/extension_set.h" // IWYU pragma: export
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/repeated_field.h" // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_mc_5frtc_5fmsgs_2eproto

namespace google
{
namespace protobuf
{
namespace internal
{
template<typename T>
::absl::string_view GetAnyMessageName();
} // namespace internal
} // namespace protobuf
} // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_mc_5frtc_5fmsgs_2eproto
{
  static const ::uint32_t offsets[];
};
extern "C"
{
  extern const ::google::protobuf::internal::DescriptorTable descriptor_table_mc_5frtc_5fmsgs_2eproto;
} // extern "C"
namespace mc_communication_msgs_proto
{
class MessageCommand;
struct MessageCommandDefaultTypeInternal;
extern MessageCommandDefaultTypeInternal _MessageCommand_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MessageCommand_class_data_;
class MessageConfig;
struct MessageConfigDefaultTypeInternal;
extern MessageConfigDefaultTypeInternal _MessageConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MessageConfig_class_data_;
class MessageEnvelope;
struct MessageEnvelopeDefaultTypeInternal;
extern MessageEnvelopeDefaultTypeInternal _MessageEnvelope_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MessageEnvelope_class_data_;
class MessageState;
struct MessageStateDefaultTypeInternal;
extern MessageStateDefaultTypeInternal _MessageState_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MessageState_class_data_;
} // namespace mc_communication_msgs_proto
namespace google
{
namespace protobuf
{
} // namespace protobuf
} // namespace google

namespace mc_communication_msgs_proto
{

// ===================================================================

// -------------------------------------------------------------------

class MessageState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mc_communication_msgs_proto.MessageState) */ {
public:
  inline MessageState() : MessageState(nullptr) {}
  ~MessageState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MessageState * PROTOBUF_NONNULL msg, ::std::destroying_delete_t)
  {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MessageState));
  }
#endif

  template<typename = void>
  explicit PROTOBUF_CONSTEXPR MessageState(::google::protobuf::internal::ConstantInitialized);

  inline MessageState(const MessageState & from) : MessageState(nullptr, from) {}
  inline MessageState(MessageState && from) noexcept : MessageState(nullptr, ::std::move(from)) {}
  inline MessageState & operator=(const MessageState & from)
  {
    CopyFrom(from);
    return *this;
  }
  inline MessageState & operator=(MessageState && from) noexcept
  {
    if(this == &from) return *this;
    if(::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena()))
    {
      InternalSwap(&from);
    }
    else
    {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet & unknown_fields() const ABSL_ATTRIBUTE_LIFETIME_BOUND
  {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
        ::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet * PROTOBUF_NONNULL mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND
  {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor * PROTOBUF_NONNULL descriptor()
  {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor * PROTOBUF_NONNULL GetDescriptor()
  {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection * PROTOBUF_NONNULL GetReflection()
  {
    return default_instance().GetMetadata().reflection;
  }
  static const MessageState & default_instance()
  {
    return *reinterpret_cast<const MessageState *>(&_MessageState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(MessageState & a, MessageState & b)
  {
    a.Swap(&b);
  }
  inline void Swap(MessageState * PROTOBUF_NONNULL other)
  {
    if(other == this) return;
    if(::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena()))
    {
      InternalSwap(other);
    }
    else
    {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageState * PROTOBUF_NONNULL other)
  {
    if(other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MessageState * PROTOBUF_NONNULL New(::google::protobuf::Arena * PROTOBUF_NULLABLE arena = nullptr) const
  {
    return ::google::protobuf::Message::DefaultConstruct<MessageState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MessageState & from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MessageState & from)
  {
    MessageState::MergeImpl(*this, from);
  }

private:
  static void MergeImpl(::google::protobuf::MessageLite & to_msg, const ::google::protobuf::MessageLite & from_msg);

public:
  bool IsInitialized() const
  {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
#if defined(PROTOBUF_CUSTOM_VTABLE)
private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite & msg);
  static ::uint8_t * PROTOBUF_NONNULL
      _InternalSerialize(const ::google::protobuf::MessageLite & msg,
                         ::uint8_t * PROTOBUF_NONNULL target,
                         ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream);

public:
  ::size_t ByteSizeLong() const
  {
    return ByteSizeLong(*this);
  }
  ::uint8_t * PROTOBUF_NONNULL
      _InternalSerialize(::uint8_t * PROTOBUF_NONNULL target,
                         ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) const
  {
    return _InternalSerialize(*this, target, stream);
  }
#else  // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t * PROTOBUF_NONNULL
      _InternalSerialize(::uint8_t * PROTOBUF_NONNULL target,
                         ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) const final;
#endif // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const
  {
    return _impl_._cached_size_.Get();
  }

private:
  void SharedCtor(::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite & self);
  void InternalSwap(MessageState * PROTOBUF_NONNULL other);

private:
  template<typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName()
  {
    return "mc_communication_msgs_proto.MessageState";
  }

protected:
  explicit MessageState(::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
  MessageState(::google::protobuf::Arena * PROTOBUF_NULLABLE arena, const MessageState & from);
  MessageState(::google::protobuf::Arena * PROTOBUF_NULLABLE arena, MessageState && from) noexcept : MessageState(arena)
  {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData * PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void * PROTOBUF_NONNULL PlacementNew_(const void * PROTOBUF_NONNULL,
                                               void * PROTOBUF_NONNULL mem,
                                               ::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int
  {
    kPositionFieldNumber = 1,
    kVelocityFieldNumber = 2,
    kTorqueFieldNumber = 3,
  };
  // repeated double position = 1;
  int position_size() const;

private:
  int _internal_position_size() const;

public:
  void clear_position();
  double position(int index) const;
  void set_position(int index, double value);
  void add_position(double value);
  const ::google::protobuf::RepeatedField<double> & position() const;
  ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL mutable_position();

private:
  const ::google::protobuf::RepeatedField<double> & _internal_position() const;
  ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL _internal_mutable_position();

public:
  // repeated double velocity = 2;
  int velocity_size() const;

private:
  int _internal_velocity_size() const;

public:
  void clear_velocity();
  double velocity(int index) const;
  void set_velocity(int index, double value);
  void add_velocity(double value);
  const ::google::protobuf::RepeatedField<double> & velocity() const;
  ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL mutable_velocity();

private:
  const ::google::protobuf::RepeatedField<double> & _internal_velocity() const;
  ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL _internal_mutable_velocity();

public:
  // repeated double torque = 3;
  int torque_size() const;

private:
  int _internal_torque_size() const;

public:
  void clear_torque();
  double torque(int index) const;
  void set_torque(int index, double value);
  void add_torque(double value);
  const ::google::protobuf::RepeatedField<double> & torque() const;
  ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL mutable_torque();

private:
  const ::google::protobuf::RepeatedField<double> & _internal_torque() const;
  ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL _internal_mutable_torque();

public:
  // @@protoc_insertion_point(class_scope:mc_communication_msgs_proto.MessageState)
private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3, 0, 0, 2> _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template<typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_
  {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena * PROTOBUF_NULLABLE arena,
                          const Impl_ & from,
                          const MessageState & from_msg);
    ::google::protobuf::RepeatedField<double> position_;
    ::google::protobuf::RepeatedField<double> velocity_;
    ::google::protobuf::RepeatedField<double> torque_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union
  {
    Impl_ _impl_;
  };
  friend struct ::TableStruct_mc_5frtc_5fmsgs_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MessageState_class_data_;
// -------------------------------------------------------------------

class MessageConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mc_communication_msgs_proto.MessageConfig) */ {
public:
  inline MessageConfig() : MessageConfig(nullptr) {}
  ~MessageConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MessageConfig * PROTOBUF_NONNULL msg, ::std::destroying_delete_t)
  {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MessageConfig));
  }
#endif

  template<typename = void>
  explicit PROTOBUF_CONSTEXPR MessageConfig(::google::protobuf::internal::ConstantInitialized);

  inline MessageConfig(const MessageConfig & from) : MessageConfig(nullptr, from) {}
  inline MessageConfig(MessageConfig && from) noexcept : MessageConfig(nullptr, ::std::move(from)) {}
  inline MessageConfig & operator=(const MessageConfig & from)
  {
    CopyFrom(from);
    return *this;
  }
  inline MessageConfig & operator=(MessageConfig && from) noexcept
  {
    if(this == &from) return *this;
    if(::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena()))
    {
      InternalSwap(&from);
    }
    else
    {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet & unknown_fields() const ABSL_ATTRIBUTE_LIFETIME_BOUND
  {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
        ::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet * PROTOBUF_NONNULL mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND
  {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor * PROTOBUF_NONNULL descriptor()
  {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor * PROTOBUF_NONNULL GetDescriptor()
  {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection * PROTOBUF_NONNULL GetReflection()
  {
    return default_instance().GetMetadata().reflection;
  }
  static const MessageConfig & default_instance()
  {
    return *reinterpret_cast<const MessageConfig *>(&_MessageConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MessageConfig & a, MessageConfig & b)
  {
    a.Swap(&b);
  }
  inline void Swap(MessageConfig * PROTOBUF_NONNULL other)
  {
    if(other == this) return;
    if(::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena()))
    {
      InternalSwap(other);
    }
    else
    {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageConfig * PROTOBUF_NONNULL other)
  {
    if(other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MessageConfig * PROTOBUF_NONNULL New(::google::protobuf::Arena * PROTOBUF_NULLABLE arena = nullptr) const
  {
    return ::google::protobuf::Message::DefaultConstruct<MessageConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MessageConfig & from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MessageConfig & from)
  {
    MessageConfig::MergeImpl(*this, from);
  }

private:
  static void MergeImpl(::google::protobuf::MessageLite & to_msg, const ::google::protobuf::MessageLite & from_msg);

public:
  bool IsInitialized() const
  {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
#if defined(PROTOBUF_CUSTOM_VTABLE)
private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite & msg);
  static ::uint8_t * PROTOBUF_NONNULL
      _InternalSerialize(const ::google::protobuf::MessageLite & msg,
                         ::uint8_t * PROTOBUF_NONNULL target,
                         ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream);

public:
  ::size_t ByteSizeLong() const
  {
    return ByteSizeLong(*this);
  }
  ::uint8_t * PROTOBUF_NONNULL
      _InternalSerialize(::uint8_t * PROTOBUF_NONNULL target,
                         ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) const
  {
    return _InternalSerialize(*this, target, stream);
  }
#else  // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t * PROTOBUF_NONNULL
      _InternalSerialize(::uint8_t * PROTOBUF_NONNULL target,
                         ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) const final;
#endif // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const
  {
    return _impl_._cached_size_.Get();
  }

private:
  void SharedCtor(::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite & self);
  void InternalSwap(MessageConfig * PROTOBUF_NONNULL other);

private:
  template<typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName()
  {
    return "mc_communication_msgs_proto.MessageConfig";
  }

protected:
  explicit MessageConfig(::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
  MessageConfig(::google::protobuf::Arena * PROTOBUF_NULLABLE arena, const MessageConfig & from);
  MessageConfig(::google::protobuf::Arena * PROTOBUF_NULLABLE arena, MessageConfig && from) noexcept
  : MessageConfig(arena)
  {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData * PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void * PROTOBUF_NONNULL PlacementNew_(const void * PROTOBUF_NONNULL,
                                               void * PROTOBUF_NONNULL mem,
                                               ::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int
  {
    kConfigFieldNumber = 1,
  };
  // string config = 1;
  void clear_config();
  const ::std::string & config() const;
  template<typename Arg_ = const ::std::string &, typename... Args_>
  void set_config(Arg_ && arg, Args_... args);
  ::std::string * PROTOBUF_NONNULL mutable_config();
  [[nodiscard]] ::std::string * PROTOBUF_NULLABLE release_config();
  void set_allocated_config(::std::string * PROTOBUF_NULLABLE value);

private:
  const ::std::string & _internal_config() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_config(const ::std::string & value);
  ::std::string * PROTOBUF_NONNULL _internal_mutable_config();

public:
  // @@protoc_insertion_point(class_scope:mc_communication_msgs_proto.MessageConfig)
private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1, 0, 56, 2> _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template<typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_
  {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena * PROTOBUF_NULLABLE arena,
                          const Impl_ & from,
                          const MessageConfig & from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr config_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union
  {
    Impl_ _impl_;
  };
  friend struct ::TableStruct_mc_5frtc_5fmsgs_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MessageConfig_class_data_;
// -------------------------------------------------------------------

class MessageCommand final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mc_communication_msgs_proto.MessageCommand) */ {
public:
  inline MessageCommand() : MessageCommand(nullptr) {}
  ~MessageCommand() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MessageCommand * PROTOBUF_NONNULL msg, ::std::destroying_delete_t)
  {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MessageCommand));
  }
#endif

  template<typename = void>
  explicit PROTOBUF_CONSTEXPR MessageCommand(::google::protobuf::internal::ConstantInitialized);

  inline MessageCommand(const MessageCommand & from) : MessageCommand(nullptr, from) {}
  inline MessageCommand(MessageCommand && from) noexcept : MessageCommand(nullptr, ::std::move(from)) {}
  inline MessageCommand & operator=(const MessageCommand & from)
  {
    CopyFrom(from);
    return *this;
  }
  inline MessageCommand & operator=(MessageCommand && from) noexcept
  {
    if(this == &from) return *this;
    if(::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena()))
    {
      InternalSwap(&from);
    }
    else
    {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet & unknown_fields() const ABSL_ATTRIBUTE_LIFETIME_BOUND
  {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
        ::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet * PROTOBUF_NONNULL mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND
  {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor * PROTOBUF_NONNULL descriptor()
  {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor * PROTOBUF_NONNULL GetDescriptor()
  {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection * PROTOBUF_NONNULL GetReflection()
  {
    return default_instance().GetMetadata().reflection;
  }
  static const MessageCommand & default_instance()
  {
    return *reinterpret_cast<const MessageCommand *>(&_MessageCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(MessageCommand & a, MessageCommand & b)
  {
    a.Swap(&b);
  }
  inline void Swap(MessageCommand * PROTOBUF_NONNULL other)
  {
    if(other == this) return;
    if(::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena()))
    {
      InternalSwap(other);
    }
    else
    {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageCommand * PROTOBUF_NONNULL other)
  {
    if(other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MessageCommand * PROTOBUF_NONNULL New(::google::protobuf::Arena * PROTOBUF_NULLABLE arena = nullptr) const
  {
    return ::google::protobuf::Message::DefaultConstruct<MessageCommand>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MessageCommand & from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MessageCommand & from)
  {
    MessageCommand::MergeImpl(*this, from);
  }

private:
  static void MergeImpl(::google::protobuf::MessageLite & to_msg, const ::google::protobuf::MessageLite & from_msg);

public:
  bool IsInitialized() const
  {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
#if defined(PROTOBUF_CUSTOM_VTABLE)
private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite & msg);
  static ::uint8_t * PROTOBUF_NONNULL
      _InternalSerialize(const ::google::protobuf::MessageLite & msg,
                         ::uint8_t * PROTOBUF_NONNULL target,
                         ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream);

public:
  ::size_t ByteSizeLong() const
  {
    return ByteSizeLong(*this);
  }
  ::uint8_t * PROTOBUF_NONNULL
      _InternalSerialize(::uint8_t * PROTOBUF_NONNULL target,
                         ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) const
  {
    return _InternalSerialize(*this, target, stream);
  }
#else  // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t * PROTOBUF_NONNULL
      _InternalSerialize(::uint8_t * PROTOBUF_NONNULL target,
                         ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) const final;
#endif // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const
  {
    return _impl_._cached_size_.Get();
  }

private:
  void SharedCtor(::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite & self);
  void InternalSwap(MessageCommand * PROTOBUF_NONNULL other);

private:
  template<typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName()
  {
    return "mc_communication_msgs_proto.MessageCommand";
  }

protected:
  explicit MessageCommand(::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
  MessageCommand(::google::protobuf::Arena * PROTOBUF_NULLABLE arena, const MessageCommand & from);
  MessageCommand(::google::protobuf::Arena * PROTOBUF_NULLABLE arena, MessageCommand && from) noexcept
  : MessageCommand(arena)
  {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData * PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void * PROTOBUF_NONNULL PlacementNew_(const void * PROTOBUF_NONNULL,
                                               void * PROTOBUF_NONNULL mem,
                                               ::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int
  {
    kPositionFieldNumber = 3,
    kVelocityFieldNumber = 4,
    kTorqueFieldNumber = 5,
    kKpFieldNumber = 1,
    kKdFieldNumber = 2,
  };
  // repeated double position = 3;
  int position_size() const;

private:
  int _internal_position_size() const;

public:
  void clear_position();
  double position(int index) const;
  void set_position(int index, double value);
  void add_position(double value);
  const ::google::protobuf::RepeatedField<double> & position() const;
  ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL mutable_position();

private:
  const ::google::protobuf::RepeatedField<double> & _internal_position() const;
  ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL _internal_mutable_position();

public:
  // repeated double velocity = 4;
  int velocity_size() const;

private:
  int _internal_velocity_size() const;

public:
  void clear_velocity();
  double velocity(int index) const;
  void set_velocity(int index, double value);
  void add_velocity(double value);
  const ::google::protobuf::RepeatedField<double> & velocity() const;
  ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL mutable_velocity();

private:
  const ::google::protobuf::RepeatedField<double> & _internal_velocity() const;
  ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL _internal_mutable_velocity();

public:
  // repeated double torque = 5;
  int torque_size() const;

private:
  int _internal_torque_size() const;

public:
  void clear_torque();
  double torque(int index) const;
  void set_torque(int index, double value);
  void add_torque(double value);
  const ::google::protobuf::RepeatedField<double> & torque() const;
  ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL mutable_torque();

private:
  const ::google::protobuf::RepeatedField<double> & _internal_torque() const;
  ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL _internal_mutable_torque();

public:
  // double kp = 1;
  void clear_kp();
  double kp() const;
  void set_kp(double value);

private:
  double _internal_kp() const;
  void _internal_set_kp(double value);

public:
  // double kd = 2;
  void clear_kd();
  double kd() const;
  void set_kd(double value);

private:
  double _internal_kd() const;
  void _internal_set_kd(double value);

public:
  // @@protoc_insertion_point(class_scope:mc_communication_msgs_proto.MessageCommand)
private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5, 0, 0, 2> _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template<typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_
  {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena * PROTOBUF_NULLABLE arena,
                          const Impl_ & from,
                          const MessageCommand & from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<double> position_;
    ::google::protobuf::RepeatedField<double> velocity_;
    ::google::protobuf::RepeatedField<double> torque_;
    double kp_;
    double kd_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union
  {
    Impl_ _impl_;
  };
  friend struct ::TableStruct_mc_5frtc_5fmsgs_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MessageCommand_class_data_;
// -------------------------------------------------------------------

class MessageEnvelope final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mc_communication_msgs_proto.MessageEnvelope) */ {
public:
  inline MessageEnvelope() : MessageEnvelope(nullptr) {}
  ~MessageEnvelope() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MessageEnvelope * PROTOBUF_NONNULL msg, ::std::destroying_delete_t)
  {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MessageEnvelope));
  }
#endif

  template<typename = void>
  explicit PROTOBUF_CONSTEXPR MessageEnvelope(::google::protobuf::internal::ConstantInitialized);

  inline MessageEnvelope(const MessageEnvelope & from) : MessageEnvelope(nullptr, from) {}
  inline MessageEnvelope(MessageEnvelope && from) noexcept : MessageEnvelope(nullptr, ::std::move(from)) {}
  inline MessageEnvelope & operator=(const MessageEnvelope & from)
  {
    CopyFrom(from);
    return *this;
  }
  inline MessageEnvelope & operator=(MessageEnvelope && from) noexcept
  {
    if(this == &from) return *this;
    if(::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena()))
    {
      InternalSwap(&from);
    }
    else
    {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet & unknown_fields() const ABSL_ATTRIBUTE_LIFETIME_BOUND
  {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
        ::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet * PROTOBUF_NONNULL mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND
  {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor * PROTOBUF_NONNULL descriptor()
  {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor * PROTOBUF_NONNULL GetDescriptor()
  {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection * PROTOBUF_NONNULL GetReflection()
  {
    return default_instance().GetMetadata().reflection;
  }
  static const MessageEnvelope & default_instance()
  {
    return *reinterpret_cast<const MessageEnvelope *>(&_MessageEnvelope_default_instance_);
  }
  enum PayloadCase
  {
    kConfig = 3,
    kState = 4,
    kCommand = 5,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(MessageEnvelope & a, MessageEnvelope & b)
  {
    a.Swap(&b);
  }
  inline void Swap(MessageEnvelope * PROTOBUF_NONNULL other)
  {
    if(other == this) return;
    if(::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena()))
    {
      InternalSwap(other);
    }
    else
    {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageEnvelope * PROTOBUF_NONNULL other)
  {
    if(other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MessageEnvelope * PROTOBUF_NONNULL New(::google::protobuf::Arena * PROTOBUF_NULLABLE arena = nullptr) const
  {
    return ::google::protobuf::Message::DefaultConstruct<MessageEnvelope>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MessageEnvelope & from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MessageEnvelope & from)
  {
    MessageEnvelope::MergeImpl(*this, from);
  }

private:
  static void MergeImpl(::google::protobuf::MessageLite & to_msg, const ::google::protobuf::MessageLite & from_msg);

public:
  bool IsInitialized() const
  {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
#if defined(PROTOBUF_CUSTOM_VTABLE)
private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite & msg);
  static ::uint8_t * PROTOBUF_NONNULL
      _InternalSerialize(const ::google::protobuf::MessageLite & msg,
                         ::uint8_t * PROTOBUF_NONNULL target,
                         ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream);

public:
  ::size_t ByteSizeLong() const
  {
    return ByteSizeLong(*this);
  }
  ::uint8_t * PROTOBUF_NONNULL
      _InternalSerialize(::uint8_t * PROTOBUF_NONNULL target,
                         ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) const
  {
    return _InternalSerialize(*this, target, stream);
  }
#else  // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t * PROTOBUF_NONNULL
      _InternalSerialize(::uint8_t * PROTOBUF_NONNULL target,
                         ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) const final;
#endif // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const
  {
    return _impl_._cached_size_.Get();
  }

private:
  void SharedCtor(::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite & self);
  void InternalSwap(MessageEnvelope * PROTOBUF_NONNULL other);

private:
  template<typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName()
  {
    return "mc_communication_msgs_proto.MessageEnvelope";
  }

protected:
  explicit MessageEnvelope(::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
  MessageEnvelope(::google::protobuf::Arena * PROTOBUF_NULLABLE arena, const MessageEnvelope & from);
  MessageEnvelope(::google::protobuf::Arena * PROTOBUF_NULLABLE arena, MessageEnvelope && from) noexcept
  : MessageEnvelope(arena)
  {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData * PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void * PROTOBUF_NONNULL PlacementNew_(const void * PROTOBUF_NONNULL,
                                               void * PROTOBUF_NONNULL mem,
                                               ::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int
  {
    kTopicFieldNumber = 1,
    kTimestampFieldNumber = 2,
    kConfigFieldNumber = 3,
    kStateFieldNumber = 4,
    kCommandFieldNumber = 5,
  };
  // string topic = 1;
  void clear_topic();
  const ::std::string & topic() const;
  template<typename Arg_ = const ::std::string &, typename... Args_>
  void set_topic(Arg_ && arg, Args_... args);
  ::std::string * PROTOBUF_NONNULL mutable_topic();
  [[nodiscard]] ::std::string * PROTOBUF_NULLABLE release_topic();
  void set_allocated_topic(::std::string * PROTOBUF_NULLABLE value);

private:
  const ::std::string & _internal_topic() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_topic(const ::std::string & value);
  ::std::string * PROTOBUF_NONNULL _internal_mutable_topic();

public:
  // uint64 timestamp = 2;
  void clear_timestamp();
  ::uint64_t timestamp() const;
  void set_timestamp(::uint64_t value);

private:
  ::uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(::uint64_t value);

public:
  // .mc_communication_msgs_proto.MessageConfig config = 3;
  bool has_config() const;

private:
  bool _internal_has_config() const;

public:
  void clear_config();
  const ::mc_communication_msgs_proto::MessageConfig & config() const;
  [[nodiscard]] ::mc_communication_msgs_proto::MessageConfig * PROTOBUF_NULLABLE release_config();
  ::mc_communication_msgs_proto::MessageConfig * PROTOBUF_NONNULL mutable_config();
  void set_allocated_config(::mc_communication_msgs_proto::MessageConfig * PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_config(::mc_communication_msgs_proto::MessageConfig * PROTOBUF_NULLABLE value);
  ::mc_communication_msgs_proto::MessageConfig * PROTOBUF_NULLABLE unsafe_arena_release_config();

private:
  const ::mc_communication_msgs_proto::MessageConfig & _internal_config() const;
  ::mc_communication_msgs_proto::MessageConfig * PROTOBUF_NONNULL _internal_mutable_config();

public:
  // .mc_communication_msgs_proto.MessageState state = 4;
  bool has_state() const;

private:
  bool _internal_has_state() const;

public:
  void clear_state();
  const ::mc_communication_msgs_proto::MessageState & state() const;
  [[nodiscard]] ::mc_communication_msgs_proto::MessageState * PROTOBUF_NULLABLE release_state();
  ::mc_communication_msgs_proto::MessageState * PROTOBUF_NONNULL mutable_state();
  void set_allocated_state(::mc_communication_msgs_proto::MessageState * PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_state(::mc_communication_msgs_proto::MessageState * PROTOBUF_NULLABLE value);
  ::mc_communication_msgs_proto::MessageState * PROTOBUF_NULLABLE unsafe_arena_release_state();

private:
  const ::mc_communication_msgs_proto::MessageState & _internal_state() const;
  ::mc_communication_msgs_proto::MessageState * PROTOBUF_NONNULL _internal_mutable_state();

public:
  // .mc_communication_msgs_proto.MessageCommand command = 5;
  bool has_command() const;

private:
  bool _internal_has_command() const;

public:
  void clear_command();
  const ::mc_communication_msgs_proto::MessageCommand & command() const;
  [[nodiscard]] ::mc_communication_msgs_proto::MessageCommand * PROTOBUF_NULLABLE release_command();
  ::mc_communication_msgs_proto::MessageCommand * PROTOBUF_NONNULL mutable_command();
  void set_allocated_command(::mc_communication_msgs_proto::MessageCommand * PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_command(::mc_communication_msgs_proto::MessageCommand * PROTOBUF_NULLABLE value);
  ::mc_communication_msgs_proto::MessageCommand * PROTOBUF_NULLABLE unsafe_arena_release_command();

private:
  const ::mc_communication_msgs_proto::MessageCommand & _internal_command() const;
  ::mc_communication_msgs_proto::MessageCommand * PROTOBUF_NONNULL _internal_mutable_command();

public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:mc_communication_msgs_proto.MessageEnvelope)
private:
  class _Internal;
  void set_has_config();
  void set_has_state();
  void set_has_command();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 5, 3, 57, 2> _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template<typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_
  {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena * PROTOBUF_NULLABLE arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena * PROTOBUF_NULLABLE arena,
                          const Impl_ & from,
                          const MessageEnvelope & from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr topic_;
    ::uint64_t timestamp_;
    union PayloadUnion
    {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message * PROTOBUF_NULLABLE config_;
      ::google::protobuf::Message * PROTOBUF_NULLABLE state_;
      ::google::protobuf::Message * PROTOBUF_NULLABLE command_;
    } payload_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union
  {
    Impl_ _impl_;
  };
  friend struct ::TableStruct_mc_5frtc_5fmsgs_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MessageEnvelope_class_data_;

// ===================================================================

// ===================================================================

#ifdef __GNUC__
#  pragma GCC diagnostic push
#  pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif // __GNUC__
// -------------------------------------------------------------------

// MessageConfig

// string config = 1;
inline void MessageConfig::clear_config()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.config_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string & MessageConfig::config() const ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageConfig.config)
  return _internal_config();
}
template<typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MessageConfig::set_config(Arg_ && arg, Args_... args)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.config_.Set(static_cast<Arg_ &&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mc_communication_msgs_proto.MessageConfig.config)
}
inline ::std::string * PROTOBUF_NONNULL MessageConfig::mutable_config() ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  ::std::string * _s = _internal_mutable_config();
  // @@protoc_insertion_point(field_mutable:mc_communication_msgs_proto.MessageConfig.config)
  return _s;
}
inline const ::std::string & MessageConfig::_internal_config() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.config_.Get();
}
inline void MessageConfig::_internal_set_config(const ::std::string & value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.config_.Set(value, GetArena());
}
inline ::std::string * PROTOBUF_NONNULL MessageConfig::_internal_mutable_config()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.config_.Mutable(GetArena());
}
inline ::std::string * PROTOBUF_NULLABLE MessageConfig::release_config()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mc_communication_msgs_proto.MessageConfig.config)
  if((_impl_._has_bits_[0] & 0x00000001U) == 0)
  {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto * released = _impl_.config_.Release();
  if(::google::protobuf::internal::DebugHardenForceCopyDefaultString())
  {
    _impl_.config_.Set("", GetArena());
  }
  return released;
}
inline void MessageConfig::set_allocated_config(::std::string * PROTOBUF_NULLABLE value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if(value != nullptr)
  {
    _impl_._has_bits_[0] |= 0x00000001U;
  }
  else
  {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.config_.SetAllocated(value, GetArena());
  if(::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.config_.IsDefault())
  {
    _impl_.config_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mc_communication_msgs_proto.MessageConfig.config)
}

// -------------------------------------------------------------------

// MessageState

// repeated double position = 1;
inline int MessageState::_internal_position_size() const
{
  return _internal_position().size();
}
inline int MessageState::position_size() const
{
  return _internal_position_size();
}
inline void MessageState::clear_position()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_.Clear();
}
inline double MessageState::position(int index) const
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageState.position)
  return _internal_position().Get(index);
}
inline void MessageState::set_position(int index, double value)
{
  _internal_mutable_position()->Set(index, value);
  // @@protoc_insertion_point(field_set:mc_communication_msgs_proto.MessageState.position)
}
inline void MessageState::add_position(double value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_position()->Add(value);
  // @@protoc_insertion_point(field_add:mc_communication_msgs_proto.MessageState.position)
}
inline const ::google::protobuf::RepeatedField<double> & MessageState::position() const ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_list:mc_communication_msgs_proto.MessageState.position)
  return _internal_position();
}
inline ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL MessageState::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_mutable_list:mc_communication_msgs_proto.MessageState.position)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_position();
}
inline const ::google::protobuf::RepeatedField<double> & MessageState::_internal_position() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_;
}
inline ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL MessageState::_internal_mutable_position()
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.position_;
}

// repeated double velocity = 2;
inline int MessageState::_internal_velocity_size() const
{
  return _internal_velocity().size();
}
inline int MessageState::velocity_size() const
{
  return _internal_velocity_size();
}
inline void MessageState::clear_velocity()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.velocity_.Clear();
}
inline double MessageState::velocity(int index) const
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageState.velocity)
  return _internal_velocity().Get(index);
}
inline void MessageState::set_velocity(int index, double value)
{
  _internal_mutable_velocity()->Set(index, value);
  // @@protoc_insertion_point(field_set:mc_communication_msgs_proto.MessageState.velocity)
}
inline void MessageState::add_velocity(double value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_velocity()->Add(value);
  // @@protoc_insertion_point(field_add:mc_communication_msgs_proto.MessageState.velocity)
}
inline const ::google::protobuf::RepeatedField<double> & MessageState::velocity() const ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_list:mc_communication_msgs_proto.MessageState.velocity)
  return _internal_velocity();
}
inline ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL MessageState::mutable_velocity()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_mutable_list:mc_communication_msgs_proto.MessageState.velocity)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_velocity();
}
inline const ::google::protobuf::RepeatedField<double> & MessageState::_internal_velocity() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.velocity_;
}
inline ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL MessageState::_internal_mutable_velocity()
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.velocity_;
}

// repeated double torque = 3;
inline int MessageState::_internal_torque_size() const
{
  return _internal_torque().size();
}
inline int MessageState::torque_size() const
{
  return _internal_torque_size();
}
inline void MessageState::clear_torque()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.torque_.Clear();
}
inline double MessageState::torque(int index) const
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageState.torque)
  return _internal_torque().Get(index);
}
inline void MessageState::set_torque(int index, double value)
{
  _internal_mutable_torque()->Set(index, value);
  // @@protoc_insertion_point(field_set:mc_communication_msgs_proto.MessageState.torque)
}
inline void MessageState::add_torque(double value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_torque()->Add(value);
  // @@protoc_insertion_point(field_add:mc_communication_msgs_proto.MessageState.torque)
}
inline const ::google::protobuf::RepeatedField<double> & MessageState::torque() const ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_list:mc_communication_msgs_proto.MessageState.torque)
  return _internal_torque();
}
inline ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL MessageState::mutable_torque()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_mutable_list:mc_communication_msgs_proto.MessageState.torque)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_torque();
}
inline const ::google::protobuf::RepeatedField<double> & MessageState::_internal_torque() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.torque_;
}
inline ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL MessageState::_internal_mutable_torque()
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.torque_;
}

// -------------------------------------------------------------------

// MessageCommand

// double kp = 1;
inline void MessageCommand::clear_kp()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.kp_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline double MessageCommand::kp() const
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageCommand.kp)
  return _internal_kp();
}
inline void MessageCommand::set_kp(double value)
{
  _internal_set_kp(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:mc_communication_msgs_proto.MessageCommand.kp)
}
inline double MessageCommand::_internal_kp() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.kp_;
}
inline void MessageCommand::_internal_set_kp(double value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.kp_ = value;
}

// double kd = 2;
inline void MessageCommand::clear_kd()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.kd_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline double MessageCommand::kd() const
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageCommand.kd)
  return _internal_kd();
}
inline void MessageCommand::set_kd(double value)
{
  _internal_set_kd(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:mc_communication_msgs_proto.MessageCommand.kd)
}
inline double MessageCommand::_internal_kd() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.kd_;
}
inline void MessageCommand::_internal_set_kd(double value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.kd_ = value;
}

// repeated double position = 3;
inline int MessageCommand::_internal_position_size() const
{
  return _internal_position().size();
}
inline int MessageCommand::position_size() const
{
  return _internal_position_size();
}
inline void MessageCommand::clear_position()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_.Clear();
}
inline double MessageCommand::position(int index) const
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageCommand.position)
  return _internal_position().Get(index);
}
inline void MessageCommand::set_position(int index, double value)
{
  _internal_mutable_position()->Set(index, value);
  // @@protoc_insertion_point(field_set:mc_communication_msgs_proto.MessageCommand.position)
}
inline void MessageCommand::add_position(double value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_position()->Add(value);
  // @@protoc_insertion_point(field_add:mc_communication_msgs_proto.MessageCommand.position)
}
inline const ::google::protobuf::RepeatedField<double> & MessageCommand::position() const ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_list:mc_communication_msgs_proto.MessageCommand.position)
  return _internal_position();
}
inline ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL MessageCommand::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_mutable_list:mc_communication_msgs_proto.MessageCommand.position)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_position();
}
inline const ::google::protobuf::RepeatedField<double> & MessageCommand::_internal_position() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_;
}
inline ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL MessageCommand::_internal_mutable_position()
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.position_;
}

// repeated double velocity = 4;
inline int MessageCommand::_internal_velocity_size() const
{
  return _internal_velocity().size();
}
inline int MessageCommand::velocity_size() const
{
  return _internal_velocity_size();
}
inline void MessageCommand::clear_velocity()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.velocity_.Clear();
}
inline double MessageCommand::velocity(int index) const
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageCommand.velocity)
  return _internal_velocity().Get(index);
}
inline void MessageCommand::set_velocity(int index, double value)
{
  _internal_mutable_velocity()->Set(index, value);
  // @@protoc_insertion_point(field_set:mc_communication_msgs_proto.MessageCommand.velocity)
}
inline void MessageCommand::add_velocity(double value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_velocity()->Add(value);
  // @@protoc_insertion_point(field_add:mc_communication_msgs_proto.MessageCommand.velocity)
}
inline const ::google::protobuf::RepeatedField<double> & MessageCommand::velocity() const ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_list:mc_communication_msgs_proto.MessageCommand.velocity)
  return _internal_velocity();
}
inline ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL MessageCommand::mutable_velocity()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_mutable_list:mc_communication_msgs_proto.MessageCommand.velocity)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_velocity();
}
inline const ::google::protobuf::RepeatedField<double> & MessageCommand::_internal_velocity() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.velocity_;
}
inline ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL MessageCommand::_internal_mutable_velocity()
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.velocity_;
}

// repeated double torque = 5;
inline int MessageCommand::_internal_torque_size() const
{
  return _internal_torque().size();
}
inline int MessageCommand::torque_size() const
{
  return _internal_torque_size();
}
inline void MessageCommand::clear_torque()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.torque_.Clear();
}
inline double MessageCommand::torque(int index) const
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageCommand.torque)
  return _internal_torque().Get(index);
}
inline void MessageCommand::set_torque(int index, double value)
{
  _internal_mutable_torque()->Set(index, value);
  // @@protoc_insertion_point(field_set:mc_communication_msgs_proto.MessageCommand.torque)
}
inline void MessageCommand::add_torque(double value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_torque()->Add(value);
  // @@protoc_insertion_point(field_add:mc_communication_msgs_proto.MessageCommand.torque)
}
inline const ::google::protobuf::RepeatedField<double> & MessageCommand::torque() const ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_list:mc_communication_msgs_proto.MessageCommand.torque)
  return _internal_torque();
}
inline ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL MessageCommand::mutable_torque()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_mutable_list:mc_communication_msgs_proto.MessageCommand.torque)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_torque();
}
inline const ::google::protobuf::RepeatedField<double> & MessageCommand::_internal_torque() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.torque_;
}
inline ::google::protobuf::RepeatedField<double> * PROTOBUF_NONNULL MessageCommand::_internal_mutable_torque()
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.torque_;
}

// -------------------------------------------------------------------

// MessageEnvelope

// string topic = 1;
inline void MessageEnvelope::clear_topic()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.topic_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string & MessageEnvelope::topic() const ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageEnvelope.topic)
  return _internal_topic();
}
template<typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MessageEnvelope::set_topic(Arg_ && arg, Args_... args)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.topic_.Set(static_cast<Arg_ &&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mc_communication_msgs_proto.MessageEnvelope.topic)
}
inline ::std::string * PROTOBUF_NONNULL MessageEnvelope::mutable_topic() ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  ::std::string * _s = _internal_mutable_topic();
  // @@protoc_insertion_point(field_mutable:mc_communication_msgs_proto.MessageEnvelope.topic)
  return _s;
}
inline const ::std::string & MessageEnvelope::_internal_topic() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.topic_.Get();
}
inline void MessageEnvelope::_internal_set_topic(const ::std::string & value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.topic_.Set(value, GetArena());
}
inline ::std::string * PROTOBUF_NONNULL MessageEnvelope::_internal_mutable_topic()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.topic_.Mutable(GetArena());
}
inline ::std::string * PROTOBUF_NULLABLE MessageEnvelope::release_topic()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mc_communication_msgs_proto.MessageEnvelope.topic)
  if((_impl_._has_bits_[0] & 0x00000001U) == 0)
  {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto * released = _impl_.topic_.Release();
  if(::google::protobuf::internal::DebugHardenForceCopyDefaultString())
  {
    _impl_.topic_.Set("", GetArena());
  }
  return released;
}
inline void MessageEnvelope::set_allocated_topic(::std::string * PROTOBUF_NULLABLE value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if(value != nullptr)
  {
    _impl_._has_bits_[0] |= 0x00000001U;
  }
  else
  {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.topic_.SetAllocated(value, GetArena());
  if(::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.topic_.IsDefault())
  {
    _impl_.topic_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mc_communication_msgs_proto.MessageEnvelope.topic)
}

// uint64 timestamp = 2;
inline void MessageEnvelope::clear_timestamp()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint64_t MessageEnvelope::timestamp() const
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageEnvelope.timestamp)
  return _internal_timestamp();
}
inline void MessageEnvelope::set_timestamp(::uint64_t value)
{
  _internal_set_timestamp(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:mc_communication_msgs_proto.MessageEnvelope.timestamp)
}
inline ::uint64_t MessageEnvelope::_internal_timestamp() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void MessageEnvelope::_internal_set_timestamp(::uint64_t value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// .mc_communication_msgs_proto.MessageConfig config = 3;
inline bool MessageEnvelope::has_config() const
{
  return payload_case() == kConfig;
}
inline bool MessageEnvelope::_internal_has_config() const
{
  return payload_case() == kConfig;
}
inline void MessageEnvelope::set_has_config()
{
  _impl_._oneof_case_[0] = kConfig;
}
inline void MessageEnvelope::clear_config()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if(payload_case() == kConfig)
  {
    if(GetArena() == nullptr)
    {
      delete _impl_.payload_.config_;
    }
    else if(::google::protobuf::internal::DebugHardenClearOneofMessageOnArena())
    {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.config_);
    }
    clear_has_payload();
  }
}
inline ::mc_communication_msgs_proto::MessageConfig * PROTOBUF_NULLABLE MessageEnvelope::release_config()
{
  // @@protoc_insertion_point(field_release:mc_communication_msgs_proto.MessageEnvelope.config)
  if(payload_case() == kConfig)
  {
    clear_has_payload();
    auto * temp = reinterpret_cast<::mc_communication_msgs_proto::MessageConfig *>(_impl_.payload_.config_);
    if(GetArena() != nullptr)
    {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.config_ = nullptr;
    return temp;
  }
  else
  {
    return nullptr;
  }
}
inline const ::mc_communication_msgs_proto::MessageConfig & MessageEnvelope::_internal_config() const
{
  return payload_case() == kConfig
             ? *reinterpret_cast<::mc_communication_msgs_proto::MessageConfig *>(_impl_.payload_.config_)
             : reinterpret_cast<::mc_communication_msgs_proto::MessageConfig &>(
                   ::mc_communication_msgs_proto::_MessageConfig_default_instance_);
}
inline const ::mc_communication_msgs_proto::MessageConfig & MessageEnvelope::config() const ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageEnvelope.config)
  return _internal_config();
}
inline ::mc_communication_msgs_proto::MessageConfig * PROTOBUF_NULLABLE MessageEnvelope::unsafe_arena_release_config()
{
  // @@protoc_insertion_point(field_unsafe_arena_release:mc_communication_msgs_proto.MessageEnvelope.config)
  if(payload_case() == kConfig)
  {
    clear_has_payload();
    auto * temp = reinterpret_cast<::mc_communication_msgs_proto::MessageConfig *>(_impl_.payload_.config_);
    _impl_.payload_.config_ = nullptr;
    return temp;
  }
  else
  {
    return nullptr;
  }
}
inline void MessageEnvelope::unsafe_arena_set_allocated_config(
    ::mc_communication_msgs_proto::MessageConfig * PROTOBUF_NULLABLE value)
{
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if(value)
  {
    set_has_config();
    _impl_.payload_.config_ = reinterpret_cast<::google::protobuf::Message *>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mc_communication_msgs_proto.MessageEnvelope.config)
}
inline ::mc_communication_msgs_proto::MessageConfig * PROTOBUF_NONNULL MessageEnvelope::_internal_mutable_config()
{
  if(payload_case() != kConfig)
  {
    clear_payload();
    set_has_config();
    _impl_.payload_.config_ = reinterpret_cast<::google::protobuf::Message *>(
        ::google::protobuf::Message::DefaultConstruct<::mc_communication_msgs_proto::MessageConfig>(GetArena()));
  }
  return reinterpret_cast<::mc_communication_msgs_proto::MessageConfig *>(_impl_.payload_.config_);
}
inline ::mc_communication_msgs_proto::MessageConfig * PROTOBUF_NONNULL MessageEnvelope::mutable_config()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  ::mc_communication_msgs_proto::MessageConfig * _msg = _internal_mutable_config();
  // @@protoc_insertion_point(field_mutable:mc_communication_msgs_proto.MessageEnvelope.config)
  return _msg;
}

// .mc_communication_msgs_proto.MessageState state = 4;
inline bool MessageEnvelope::has_state() const
{
  return payload_case() == kState;
}
inline bool MessageEnvelope::_internal_has_state() const
{
  return payload_case() == kState;
}
inline void MessageEnvelope::set_has_state()
{
  _impl_._oneof_case_[0] = kState;
}
inline void MessageEnvelope::clear_state()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if(payload_case() == kState)
  {
    if(GetArena() == nullptr)
    {
      delete _impl_.payload_.state_;
    }
    else if(::google::protobuf::internal::DebugHardenClearOneofMessageOnArena())
    {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.state_);
    }
    clear_has_payload();
  }
}
inline ::mc_communication_msgs_proto::MessageState * PROTOBUF_NULLABLE MessageEnvelope::release_state()
{
  // @@protoc_insertion_point(field_release:mc_communication_msgs_proto.MessageEnvelope.state)
  if(payload_case() == kState)
  {
    clear_has_payload();
    auto * temp = reinterpret_cast<::mc_communication_msgs_proto::MessageState *>(_impl_.payload_.state_);
    if(GetArena() != nullptr)
    {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.state_ = nullptr;
    return temp;
  }
  else
  {
    return nullptr;
  }
}
inline const ::mc_communication_msgs_proto::MessageState & MessageEnvelope::_internal_state() const
{
  return payload_case() == kState
             ? *reinterpret_cast<::mc_communication_msgs_proto::MessageState *>(_impl_.payload_.state_)
             : reinterpret_cast<::mc_communication_msgs_proto::MessageState &>(
                   ::mc_communication_msgs_proto::_MessageState_default_instance_);
}
inline const ::mc_communication_msgs_proto::MessageState & MessageEnvelope::state() const ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageEnvelope.state)
  return _internal_state();
}
inline ::mc_communication_msgs_proto::MessageState * PROTOBUF_NULLABLE MessageEnvelope::unsafe_arena_release_state()
{
  // @@protoc_insertion_point(field_unsafe_arena_release:mc_communication_msgs_proto.MessageEnvelope.state)
  if(payload_case() == kState)
  {
    clear_has_payload();
    auto * temp = reinterpret_cast<::mc_communication_msgs_proto::MessageState *>(_impl_.payload_.state_);
    _impl_.payload_.state_ = nullptr;
    return temp;
  }
  else
  {
    return nullptr;
  }
}
inline void MessageEnvelope::unsafe_arena_set_allocated_state(
    ::mc_communication_msgs_proto::MessageState * PROTOBUF_NULLABLE value)
{
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if(value)
  {
    set_has_state();
    _impl_.payload_.state_ = reinterpret_cast<::google::protobuf::Message *>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mc_communication_msgs_proto.MessageEnvelope.state)
}
inline ::mc_communication_msgs_proto::MessageState * PROTOBUF_NONNULL MessageEnvelope::_internal_mutable_state()
{
  if(payload_case() != kState)
  {
    clear_payload();
    set_has_state();
    _impl_.payload_.state_ = reinterpret_cast<::google::protobuf::Message *>(
        ::google::protobuf::Message::DefaultConstruct<::mc_communication_msgs_proto::MessageState>(GetArena()));
  }
  return reinterpret_cast<::mc_communication_msgs_proto::MessageState *>(_impl_.payload_.state_);
}
inline ::mc_communication_msgs_proto::MessageState * PROTOBUF_NONNULL MessageEnvelope::mutable_state()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  ::mc_communication_msgs_proto::MessageState * _msg = _internal_mutable_state();
  // @@protoc_insertion_point(field_mutable:mc_communication_msgs_proto.MessageEnvelope.state)
  return _msg;
}

// .mc_communication_msgs_proto.MessageCommand command = 5;
inline bool MessageEnvelope::has_command() const
{
  return payload_case() == kCommand;
}
inline bool MessageEnvelope::_internal_has_command() const
{
  return payload_case() == kCommand;
}
inline void MessageEnvelope::set_has_command()
{
  _impl_._oneof_case_[0] = kCommand;
}
inline void MessageEnvelope::clear_command()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if(payload_case() == kCommand)
  {
    if(GetArena() == nullptr)
    {
      delete _impl_.payload_.command_;
    }
    else if(::google::protobuf::internal::DebugHardenClearOneofMessageOnArena())
    {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.command_);
    }
    clear_has_payload();
  }
}
inline ::mc_communication_msgs_proto::MessageCommand * PROTOBUF_NULLABLE MessageEnvelope::release_command()
{
  // @@protoc_insertion_point(field_release:mc_communication_msgs_proto.MessageEnvelope.command)
  if(payload_case() == kCommand)
  {
    clear_has_payload();
    auto * temp = reinterpret_cast<::mc_communication_msgs_proto::MessageCommand *>(_impl_.payload_.command_);
    if(GetArena() != nullptr)
    {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.command_ = nullptr;
    return temp;
  }
  else
  {
    return nullptr;
  }
}
inline const ::mc_communication_msgs_proto::MessageCommand & MessageEnvelope::_internal_command() const
{
  return payload_case() == kCommand
             ? *reinterpret_cast<::mc_communication_msgs_proto::MessageCommand *>(_impl_.payload_.command_)
             : reinterpret_cast<::mc_communication_msgs_proto::MessageCommand &>(
                   ::mc_communication_msgs_proto::_MessageCommand_default_instance_);
}
inline const ::mc_communication_msgs_proto::MessageCommand & MessageEnvelope::command() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_get:mc_communication_msgs_proto.MessageEnvelope.command)
  return _internal_command();
}
inline ::mc_communication_msgs_proto::MessageCommand * PROTOBUF_NULLABLE MessageEnvelope::unsafe_arena_release_command()
{
  // @@protoc_insertion_point(field_unsafe_arena_release:mc_communication_msgs_proto.MessageEnvelope.command)
  if(payload_case() == kCommand)
  {
    clear_has_payload();
    auto * temp = reinterpret_cast<::mc_communication_msgs_proto::MessageCommand *>(_impl_.payload_.command_);
    _impl_.payload_.command_ = nullptr;
    return temp;
  }
  else
  {
    return nullptr;
  }
}
inline void MessageEnvelope::unsafe_arena_set_allocated_command(
    ::mc_communication_msgs_proto::MessageCommand * PROTOBUF_NULLABLE value)
{
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if(value)
  {
    set_has_command();
    _impl_.payload_.command_ = reinterpret_cast<::google::protobuf::Message *>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mc_communication_msgs_proto.MessageEnvelope.command)
}
inline ::mc_communication_msgs_proto::MessageCommand * PROTOBUF_NONNULL MessageEnvelope::_internal_mutable_command()
{
  if(payload_case() != kCommand)
  {
    clear_payload();
    set_has_command();
    _impl_.payload_.command_ = reinterpret_cast<::google::protobuf::Message *>(
        ::google::protobuf::Message::DefaultConstruct<::mc_communication_msgs_proto::MessageCommand>(GetArena()));
  }
  return reinterpret_cast<::mc_communication_msgs_proto::MessageCommand *>(_impl_.payload_.command_);
}
inline ::mc_communication_msgs_proto::MessageCommand * PROTOBUF_NONNULL MessageEnvelope::mutable_command()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  ::mc_communication_msgs_proto::MessageCommand * _msg = _internal_mutable_command();
  // @@protoc_insertion_point(field_mutable:mc_communication_msgs_proto.MessageEnvelope.command)
  return _msg;
}

inline bool MessageEnvelope::has_payload() const
{
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void MessageEnvelope::clear_has_payload()
{
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline MessageEnvelope::PayloadCase MessageEnvelope::payload_case() const
{
  return MessageEnvelope::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#  pragma GCC diagnostic pop
#endif // __GNUC__

// @@protoc_insertion_point(namespace_scope)
} // namespace mc_communication_msgs_proto

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif // mc_5frtc_5fmsgs_2eproto_2epb_2eh
