// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc_rtc_msgs.proto
// Protobuf C++ Version: 6.32.0-rc2

#include "mc_rtc_msgs.pb.h"

#include "google/protobuf/descriptor.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/wire_format_lite.h"
#include <algorithm>
#include <type_traits>
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace mc_communication_msgs_proto
{

inline constexpr MessageState::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
: position_{}, velocity_{}, torque_{}, _cached_size_{0}
{
}

template<typename>
PROTOBUF_CONSTEXPR MessageState::MessageState(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
: ::google::protobuf::Message(MessageState_class_data_.base()),
#else  // PROTOBUF_CUSTOM_VTABLE
: ::google::protobuf::Message(),
#endif // PROTOBUF_CUSTOM_VTABLE
  _impl_(::_pbi::ConstantInitialized())
{
}
struct MessageStateDefaultTypeInternal
{
  PROTOBUF_CONSTEXPR MessageStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageStateDefaultTypeInternal() {}
  union
  {
    MessageState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageStateDefaultTypeInternal
    _MessageState_default_instance_;

inline constexpr MessageConfig::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
: _cached_size_{0}, config_(&::google::protobuf::internal::fixed_address_empty_string, ::_pbi::ConstantInitialized())
{
}

template<typename>
PROTOBUF_CONSTEXPR MessageConfig::MessageConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
: ::google::protobuf::Message(MessageConfig_class_data_.base()),
#else  // PROTOBUF_CUSTOM_VTABLE
: ::google::protobuf::Message(),
#endif // PROTOBUF_CUSTOM_VTABLE
  _impl_(::_pbi::ConstantInitialized())
{
}
struct MessageConfigDefaultTypeInternal
{
  PROTOBUF_CONSTEXPR MessageConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageConfigDefaultTypeInternal() {}
  union
  {
    MessageConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageConfigDefaultTypeInternal
    _MessageConfig_default_instance_;

inline constexpr MessageCommand::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
: _cached_size_{0}, position_{}, velocity_{}, torque_{}, kp_{0}, kd_{0}
{
}

template<typename>
PROTOBUF_CONSTEXPR MessageCommand::MessageCommand(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
: ::google::protobuf::Message(MessageCommand_class_data_.base()),
#else  // PROTOBUF_CUSTOM_VTABLE
: ::google::protobuf::Message(),
#endif // PROTOBUF_CUSTOM_VTABLE
  _impl_(::_pbi::ConstantInitialized())
{
}
struct MessageCommandDefaultTypeInternal
{
  PROTOBUF_CONSTEXPR MessageCommandDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageCommandDefaultTypeInternal() {}
  union
  {
    MessageCommand _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageCommandDefaultTypeInternal
    _MessageCommand_default_instance_;

inline constexpr MessageEnvelope::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
: _cached_size_{0}, topic_(&::google::protobuf::internal::fixed_address_empty_string, ::_pbi::ConstantInitialized()),
  timestamp_{::uint64_t{0u}}, payload_{}, _oneof_case_{}
{
}

template<typename>
PROTOBUF_CONSTEXPR MessageEnvelope::MessageEnvelope(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
: ::google::protobuf::Message(MessageEnvelope_class_data_.base()),
#else  // PROTOBUF_CUSTOM_VTABLE
: ::google::protobuf::Message(),
#endif // PROTOBUF_CUSTOM_VTABLE
  _impl_(::_pbi::ConstantInitialized())
{
}
struct MessageEnvelopeDefaultTypeInternal
{
  PROTOBUF_CONSTEXPR MessageEnvelopeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageEnvelopeDefaultTypeInternal() {}
  union
  {
    MessageEnvelope _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageEnvelopeDefaultTypeInternal
    _MessageEnvelope_default_instance_;
} // namespace mc_communication_msgs_proto
static constexpr const ::_pb::EnumDescriptor * PROTOBUF_NONNULL * PROTOBUF_NULLABLE
    file_level_enum_descriptors_mc_5frtc_5fmsgs_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor * PROTOBUF_NONNULL * PROTOBUF_NULLABLE
    file_level_service_descriptors_mc_5frtc_5fmsgs_2eproto = nullptr;
const ::uint32_t TableStruct_mc_5frtc_5fmsgs_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
    0x081, // bitmap
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageConfig, _impl_._has_bits_),
    4, // hasbit index offset
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageConfig, _impl_.config_),
    0,
    0x000, // bitmap
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageState, _impl_.position_),
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageState, _impl_.velocity_),
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageState, _impl_.torque_),
    0x081, // bitmap
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageCommand, _impl_._has_bits_),
    8, // hasbit index offset
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageCommand, _impl_.kp_),
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageCommand, _impl_.kd_),
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageCommand, _impl_.position_),
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageCommand, _impl_.velocity_),
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageCommand, _impl_.torque_),
    0,
    1,
    ~0u,
    ~0u,
    ~0u,
    0x085, // bitmap
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageEnvelope, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageEnvelope, _impl_._oneof_case_[0]),
    10, // hasbit index offset
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageEnvelope, _impl_.topic_),
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageEnvelope, _impl_.timestamp_),
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageEnvelope, _impl_.payload_),
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageEnvelope, _impl_.payload_),
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageEnvelope, _impl_.payload_),
    PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageEnvelope, _impl_.payload_),
    0,
    1,
    ~0u,
    ~0u,
    ~0u,
};

static const ::_pbi::MigrationSchema schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
    {0, sizeof(::mc_communication_msgs_proto::MessageConfig)},
    {5, sizeof(::mc_communication_msgs_proto::MessageState)},
    {9, sizeof(::mc_communication_msgs_proto::MessageCommand)},
    {22, sizeof(::mc_communication_msgs_proto::MessageEnvelope)},
};
static const ::_pb::Message * PROTOBUF_NONNULL const file_default_instances[] = {
    &::mc_communication_msgs_proto::_MessageConfig_default_instance_._instance,
    &::mc_communication_msgs_proto::_MessageState_default_instance_._instance,
    &::mc_communication_msgs_proto::_MessageCommand_default_instance_._instance,
    &::mc_communication_msgs_proto::_MessageEnvelope_default_instance_._instance,
};
const char descriptor_table_protodef_mc_5frtc_5fmsgs_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
    "\n\021mc_rtc_msgs.proto\022\033mc_communication_ms"
    "gs_proto\"\037\n\rMessageConfig\022\016\n\006config\030\001 \001("
    "\t\"B\n\014MessageState\022\020\n\010position\030\001 \003(\001\022\020\n\010v"
    "elocity\030\002 \003(\001\022\016\n\006torque\030\003 \003(\001\"\\\n\016Message"
    "Command\022\n\n\002kp\030\001 \001(\001\022\n\n\002kd\030\002 \001(\001\022\020\n\010posit"
    "ion\030\003 \003(\001\022\020\n\010velocity\030\004 \003(\001\022\016\n\006torque\030\005 "
    "\003(\001\"\370\001\n\017MessageEnvelope\022\r\n\005topic\030\001 \001(\t\022\021"
    "\n\ttimestamp\030\002 \001(\004\022<\n\006config\030\003 \001(\0132*.mc_c"
    "ommunication_msgs_proto.MessageConfigH\000\022"
    ":\n\005state\030\004 \001(\0132).mc_communication_msgs_p"
    "roto.MessageStateH\000\022>\n\007command\030\005 \001(\0132+.m"
    "c_communication_msgs_proto.MessageComman"
    "dH\000B\t\n\007payloadb\006proto3"};
static ::absl::once_flag descriptor_table_mc_5frtc_5fmsgs_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_mc_5frtc_5fmsgs_2eproto = {
    false,
    false,
    502,
    descriptor_table_protodef_mc_5frtc_5fmsgs_2eproto,
    "mc_rtc_msgs.proto",
    &descriptor_table_mc_5frtc_5fmsgs_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_mc_5frtc_5fmsgs_2eproto::offsets,
    file_level_enum_descriptors_mc_5frtc_5fmsgs_2eproto,
    file_level_service_descriptors_mc_5frtc_5fmsgs_2eproto,
};
namespace mc_communication_msgs_proto
{
// ===================================================================

class MessageConfig::_Internal
{
public:
  using HasBits = decltype(::std::declval<MessageConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset = 8 * PROTOBUF_FIELD_OFFSET(MessageConfig, _impl_._has_bits_);
};

MessageConfig::MessageConfig(::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
: ::google::protobuf::Message(arena, MessageConfig_class_data_.base())
{
#else  // PROTOBUF_CUSTOM_VTABLE
: ::google::protobuf::Message(arena)
{
#endif // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mc_communication_msgs_proto.MessageConfig)
}
PROTOBUF_NDEBUG_INLINE MessageConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena,
    const Impl_ & from,
    [[maybe_unused]] const ::mc_communication_msgs_proto::MessageConfig & from_msg)
: _has_bits_{from._has_bits_}, _cached_size_{0}, config_(arena, from.config_)
{
}

MessageConfig::MessageConfig(::google::protobuf::Arena * PROTOBUF_NULLABLE arena, const MessageConfig & from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
: ::google::protobuf::Message(arena, MessageConfig_class_data_.base())
{
#else  // PROTOBUF_CUSTOM_VTABLE
: ::google::protobuf::Message(arena)
{
#endif // PROTOBUF_CUSTOM_VTABLE
  MessageConfig * const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
  new(&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:mc_communication_msgs_proto.MessageConfig)
}
PROTOBUF_NDEBUG_INLINE MessageConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
: _cached_size_{0}, config_(arena)
{
}

inline void MessageConfig::SharedCtor(::_pb::Arena * PROTOBUF_NULLABLE arena)
{
  new(&_impl_) Impl_(internal_visibility(), arena);
}
MessageConfig::~MessageConfig()
{
  // @@protoc_insertion_point(destructor:mc_communication_msgs_proto.MessageConfig)
  SharedDtor(*this);
}
inline void MessageConfig::SharedDtor(MessageLite & self)
{
  MessageConfig & this_ = static_cast<MessageConfig &>(self);
  if constexpr(::_pbi::DebugHardenVerifyHasBitConsistency())
  {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.config_.Destroy();
  this_._impl_.~Impl_();
}

inline void * PROTOBUF_NONNULL MessageConfig::PlacementNew_(const void * PROTOBUF_NONNULL,
                                                            void * PROTOBUF_NONNULL mem,
                                                            ::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
{
  return ::new(mem) MessageConfig(arena);
}
constexpr auto MessageConfig::InternalNewImpl_()
{
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MessageConfig), alignof(MessageConfig));
}
constexpr auto MessageConfig::InternalGenerateClassData_()
{
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MessageConfig_default_instance_._instance,
          &_table_.header,
          nullptr, // OnDemandRegisterArenaDtor
          nullptr, // IsInitialized
          &MessageConfig::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MessageConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MessageConfig::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MessageConfig>(),
          &MessageConfig::ByteSizeLong,
          &MessageConfig::_InternalSerialize,
#endif // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MessageConfig, _impl_._cached_size_),
          false,
      },
      &MessageConfig::kDescriptorMethods,
      &descriptor_table_mc_5frtc_5fmsgs_2eproto,
      nullptr, // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
    MessageConfig_class_data_ = MessageConfig::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData * PROTOBUF_NONNULL
    MessageConfig::GetClassData() const
{
  ::google::protobuf::internal::PrefetchToLocalCache(&MessageConfig_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MessageConfig_class_data_.tc_table);
  return MessageConfig_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<0, 1, 0, 56, 2> MessageConfig::_table_ =
    {
        {
            PROTOBUF_FIELD_OFFSET(MessageConfig, _impl_._has_bits_),
            0, // no _extensions_
            1,
            0, // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967294, // skipmap
            offsetof(decltype(_table_), field_entries),
            1,                                        // num_field_entries
            0,                                        // num_aux_entries
            offsetof(decltype(_table_), field_names), // no aux_entries
            MessageConfig_class_data_.base(),
            nullptr,                           // post_loop_handler
            ::_pbi::TcParser::GenericFallback, // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::mc_communication_msgs_proto::MessageConfig>(), // to_prefetch
#endif                                                                                  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // string config = 1;
            {::_pbi::TcParser::FastUS1, {10, 0, 0, PROTOBUF_FIELD_OFFSET(MessageConfig, _impl_.config_)}},
        }},
        {{65535, 65535}},
        {{
            // string config = 1;
            {PROTOBUF_FIELD_OFFSET(MessageConfig, _impl_.config_), _Internal::kHasBitsOffset + 0, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
        }},
        // no aux_entries
        {{"\51\6\0\0\0\0\0\0"
          "mc_communication_msgs_proto.MessageConfig"
          "config"}},
    };
PROTOBUF_NOINLINE void MessageConfig::Clear()
{
  // @@protoc_insertion_point(message_clear_start:mc_communication_msgs_proto.MessageConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if((cached_has_bits & 0x00000001U) != 0)
  {
    _impl_.config_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t * PROTOBUF_NONNULL
    MessageConfig::_InternalSerialize(const ::google::protobuf::MessageLite & base,
                                      ::uint8_t * PROTOBUF_NONNULL target,
                                      ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream)
{
  const MessageConfig & this_ = static_cast<const MessageConfig &>(base);
#else  // PROTOBUF_CUSTOM_VTABLE
::uint8_t * PROTOBUF_NONNULL
    MessageConfig::_InternalSerialize(::uint8_t * PROTOBUF_NONNULL target,
                                      ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) const
{
  const MessageConfig & this_ = *this;
#endif // PROTOBUF_CUSTOM_VTABLE
  if constexpr(::_pbi::DebugHardenVerifyHasBitConsistency())
  {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:mc_communication_msgs_proto.MessageConfig)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string config = 1;
  if((this_._impl_._has_bits_[0] & 0x00000001U) != 0)
  {
    if(!this_._internal_config().empty())
    {
      const ::std::string & _s = this_._internal_config();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "mc_communication_msgs_proto.MessageConfig.config");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if(ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields()))
  {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
            ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mc_communication_msgs_proto.MessageConfig)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MessageConfig::ByteSizeLong(const MessageLite & base)
{
  const MessageConfig & this_ = static_cast<const MessageConfig &>(base);
#else  // PROTOBUF_CUSTOM_VTABLE
::size_t MessageConfig::ByteSizeLong() const
{
  const MessageConfig & this_ = *this;
#endif // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mc_communication_msgs_proto.MessageConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  {
    // string config = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if((cached_has_bits & 0x00000001U) != 0)
    {
      if(!this_._internal_config().empty())
      {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(this_._internal_config());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size, &this_._impl_._cached_size_);
}

void MessageConfig::MergeImpl(::google::protobuf::MessageLite & to_msg,
                              const ::google::protobuf::MessageLite & from_msg)
{
  auto * const _this = static_cast<MessageConfig *>(&to_msg);
  auto & from = static_cast<const MessageConfig &>(from_msg);
  if constexpr(::_pbi::DebugHardenVerifyHasBitConsistency())
  {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:mc_communication_msgs_proto.MessageConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if((cached_has_bits & 0x00000001U) != 0)
  {
    if(!from._internal_config().empty())
    {
      _this->_internal_set_config(from._internal_config());
    }
    else
    {
      if(_this->_impl_.config_.IsDefault())
      {
        _this->_internal_set_config("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MessageConfig::CopyFrom(const MessageConfig & from)
{
  // @@protoc_insertion_point(class_specific_copy_from_start:mc_communication_msgs_proto.MessageConfig)
  if(&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageConfig::InternalSwap(MessageConfig * PROTOBUF_RESTRICT PROTOBUF_NONNULL other)
{
  using ::std::swap;
  auto * arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.config_, &other->_impl_.config_, arena);
}

::google::protobuf::Metadata MessageConfig::GetMetadata() const
{
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MessageState::_Internal
{
public:
};

MessageState::MessageState(::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
: ::google::protobuf::Message(arena, MessageState_class_data_.base())
{
#else  // PROTOBUF_CUSTOM_VTABLE
: ::google::protobuf::Message(arena)
{
#endif // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mc_communication_msgs_proto.MessageState)
}
PROTOBUF_NDEBUG_INLINE MessageState::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena,
    const Impl_ & from,
    [[maybe_unused]] const ::mc_communication_msgs_proto::MessageState & from_msg)
: position_{visibility, arena, from.position_}, velocity_{visibility, arena, from.velocity_},
  torque_{visibility, arena, from.torque_}, _cached_size_{0}
{
}

MessageState::MessageState(::google::protobuf::Arena * PROTOBUF_NULLABLE arena, const MessageState & from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
: ::google::protobuf::Message(arena, MessageState_class_data_.base())
{
#else  // PROTOBUF_CUSTOM_VTABLE
: ::google::protobuf::Message(arena)
{
#endif // PROTOBUF_CUSTOM_VTABLE
  MessageState * const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
  new(&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:mc_communication_msgs_proto.MessageState)
}
PROTOBUF_NDEBUG_INLINE MessageState::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
: position_{visibility, arena}, velocity_{visibility, arena}, torque_{visibility, arena}, _cached_size_{0}
{
}

inline void MessageState::SharedCtor(::_pb::Arena * PROTOBUF_NULLABLE arena)
{
  new(&_impl_) Impl_(internal_visibility(), arena);
}
MessageState::~MessageState()
{
  // @@protoc_insertion_point(destructor:mc_communication_msgs_proto.MessageState)
  SharedDtor(*this);
}
inline void MessageState::SharedDtor(MessageLite & self)
{
  MessageState & this_ = static_cast<MessageState &>(self);
  if constexpr(::_pbi::DebugHardenVerifyHasBitConsistency())
  {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void * PROTOBUF_NONNULL MessageState::PlacementNew_(const void * PROTOBUF_NONNULL,
                                                           void * PROTOBUF_NONNULL mem,
                                                           ::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
{
  return ::new(mem) MessageState(arena);
}
constexpr auto MessageState::InternalNewImpl_()
{
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(MessageState, _impl_.position_)
          + decltype(MessageState::_impl_.position_)::InternalGetArenaOffset(
              ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(MessageState, _impl_.velocity_)
          + decltype(MessageState::_impl_.velocity_)::InternalGetArenaOffset(
              ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(MessageState, _impl_.torque_)
          + decltype(MessageState::_impl_.torque_)::InternalGetArenaOffset(
              ::google::protobuf::Message::internal_visibility()),
  });
  if(arena_bits.has_value())
  {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MessageState), alignof(MessageState),
                                                                  *arena_bits);
  }
  else
  {
    return ::google::protobuf::internal::MessageCreator(&MessageState::PlacementNew_, sizeof(MessageState),
                                                        alignof(MessageState));
  }
}
constexpr auto MessageState::InternalGenerateClassData_()
{
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MessageState_default_instance_._instance,
          &_table_.header,
          nullptr, // OnDemandRegisterArenaDtor
          nullptr, // IsInitialized
          &MessageState::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MessageState>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MessageState::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MessageState>(),
          &MessageState::ByteSizeLong,
          &MessageState::_InternalSerialize,
#endif // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MessageState, _impl_._cached_size_),
          false,
      },
      &MessageState::kDescriptorMethods,
      &descriptor_table_mc_5frtc_5fmsgs_2eproto,
      nullptr, // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
    MessageState_class_data_ = MessageState::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData * PROTOBUF_NONNULL
    MessageState::GetClassData() const
{
  ::google::protobuf::internal::PrefetchToLocalCache(&MessageState_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MessageState_class_data_.tc_table);
  return MessageState_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<2, 3, 0, 0, 2> MessageState::_table_ = {
    {
        0, // no _has_bits_
        0, // no _extensions_
        3,
        24, // max_field_number, fast_idx_mask
        offsetof(decltype(_table_), field_lookup_table),
        4294967288, // skipmap
        offsetof(decltype(_table_), field_entries),
        3,                                        // num_field_entries
        0,                                        // num_aux_entries
        offsetof(decltype(_table_), field_names), // no aux_entries
        MessageState_class_data_.base(),
        nullptr,                           // post_loop_handler
        ::_pbi::TcParser::GenericFallback, // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
        ::_pbi::TcParser::GetTable<::mc_communication_msgs_proto::MessageState>(), // to_prefetch
#endif                                                                             // PROTOBUF_PREFETCH_PARSE_TABLE
    },
    {{
        {::_pbi::TcParser::MiniParse, {}},
        // repeated double position = 1;
        {::_pbi::TcParser::FastF64P1, {10, 63, 0, PROTOBUF_FIELD_OFFSET(MessageState, _impl_.position_)}},
        // repeated double velocity = 2;
        {::_pbi::TcParser::FastF64P1, {18, 63, 0, PROTOBUF_FIELD_OFFSET(MessageState, _impl_.velocity_)}},
        // repeated double torque = 3;
        {::_pbi::TcParser::FastF64P1, {26, 63, 0, PROTOBUF_FIELD_OFFSET(MessageState, _impl_.torque_)}},
    }},
    {{65535, 65535}},
    {{
        // repeated double position = 1;
        {PROTOBUF_FIELD_OFFSET(MessageState, _impl_.position_), 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
        // repeated double velocity = 2;
        {PROTOBUF_FIELD_OFFSET(MessageState, _impl_.velocity_), 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
        // repeated double torque = 3;
        {PROTOBUF_FIELD_OFFSET(MessageState, _impl_.torque_), 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    }},
    // no aux_entries
    {{}},
};
PROTOBUF_NOINLINE void MessageState::Clear()
{
  // @@protoc_insertion_point(message_clear_start:mc_communication_msgs_proto.MessageState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  _impl_.position_.Clear();
  _impl_.velocity_.Clear();
  _impl_.torque_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t * PROTOBUF_NONNULL
    MessageState::_InternalSerialize(const ::google::protobuf::MessageLite & base,
                                     ::uint8_t * PROTOBUF_NONNULL target,
                                     ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream)
{
  const MessageState & this_ = static_cast<const MessageState &>(base);
#else  // PROTOBUF_CUSTOM_VTABLE
::uint8_t * PROTOBUF_NONNULL
    MessageState::_InternalSerialize(::uint8_t * PROTOBUF_NONNULL target,
                                     ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) const
{
  const MessageState & this_ = *this;
#endif // PROTOBUF_CUSTOM_VTABLE
  if constexpr(::_pbi::DebugHardenVerifyHasBitConsistency())
  {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:mc_communication_msgs_proto.MessageState)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated double position = 1;
  if(this_._internal_position_size() > 0)
  {
    target = stream->WriteFixedPacked(1, this_._internal_position(), target);
  }

  // repeated double velocity = 2;
  if(this_._internal_velocity_size() > 0)
  {
    target = stream->WriteFixedPacked(2, this_._internal_velocity(), target);
  }

  // repeated double torque = 3;
  if(this_._internal_torque_size() > 0)
  {
    target = stream->WriteFixedPacked(3, this_._internal_torque(), target);
  }

  if(ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields()))
  {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
            ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mc_communication_msgs_proto.MessageState)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MessageState::ByteSizeLong(const MessageLite & base)
{
  const MessageState & this_ = static_cast<const MessageState &>(base);
#else  // PROTOBUF_CUSTOM_VTABLE
::size_t MessageState::ByteSizeLong() const
{
  const MessageState & this_ = *this;
#endif // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mc_communication_msgs_proto.MessageState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  {
    // repeated double position = 1;
    {
      ::size_t data_size = ::size_t{8} * ::_pbi::FromIntSize(this_._internal_position_size());
      ::size_t tag_size = data_size == 0 ? 0 : 1 + ::_pbi::WireFormatLite::Int32Size(static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double velocity = 2;
    {
      ::size_t data_size = ::size_t{8} * ::_pbi::FromIntSize(this_._internal_velocity_size());
      ::size_t tag_size = data_size == 0 ? 0 : 1 + ::_pbi::WireFormatLite::Int32Size(static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double torque = 3;
    {
      ::size_t data_size = ::size_t{8} * ::_pbi::FromIntSize(this_._internal_torque_size());
      ::size_t tag_size = data_size == 0 ? 0 : 1 + ::_pbi::WireFormatLite::Int32Size(static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size, &this_._impl_._cached_size_);
}

void MessageState::MergeImpl(::google::protobuf::MessageLite & to_msg, const ::google::protobuf::MessageLite & from_msg)
{
  auto * const _this = static_cast<MessageState *>(&to_msg);
  auto & from = static_cast<const MessageState &>(from_msg);
  if constexpr(::_pbi::DebugHardenVerifyHasBitConsistency())
  {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:mc_communication_msgs_proto.MessageState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  _this->_internal_mutable_position()->MergeFrom(from._internal_position());
  _this->_internal_mutable_velocity()->MergeFrom(from._internal_velocity());
  _this->_internal_mutable_torque()->MergeFrom(from._internal_torque());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MessageState::CopyFrom(const MessageState & from)
{
  // @@protoc_insertion_point(class_specific_copy_from_start:mc_communication_msgs_proto.MessageState)
  if(&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageState::InternalSwap(MessageState * PROTOBUF_RESTRICT PROTOBUF_NONNULL other)
{
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.position_.InternalSwap(&other->_impl_.position_);
  _impl_.velocity_.InternalSwap(&other->_impl_.velocity_);
  _impl_.torque_.InternalSwap(&other->_impl_.torque_);
}

::google::protobuf::Metadata MessageState::GetMetadata() const
{
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MessageCommand::_Internal
{
public:
  using HasBits = decltype(::std::declval<MessageCommand>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset = 8 * PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_._has_bits_);
};

MessageCommand::MessageCommand(::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
: ::google::protobuf::Message(arena, MessageCommand_class_data_.base())
{
#else  // PROTOBUF_CUSTOM_VTABLE
: ::google::protobuf::Message(arena)
{
#endif // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mc_communication_msgs_proto.MessageCommand)
}
PROTOBUF_NDEBUG_INLINE MessageCommand::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena,
    const Impl_ & from,
    [[maybe_unused]] const ::mc_communication_msgs_proto::MessageCommand & from_msg)
: _has_bits_{from._has_bits_}, _cached_size_{0}, position_{visibility, arena, from.position_},
  velocity_{visibility, arena, from.velocity_}, torque_{visibility, arena, from.torque_}
{
}

MessageCommand::MessageCommand(::google::protobuf::Arena * PROTOBUF_NULLABLE arena, const MessageCommand & from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
: ::google::protobuf::Message(arena, MessageCommand_class_data_.base())
{
#else  // PROTOBUF_CUSTOM_VTABLE
: ::google::protobuf::Message(arena)
{
#endif // PROTOBUF_CUSTOM_VTABLE
  MessageCommand * const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
  new(&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) + offsetof(Impl_, kp_),
           reinterpret_cast<const char *>(&from._impl_) + offsetof(Impl_, kp_),
           offsetof(Impl_, kd_) - offsetof(Impl_, kp_) + sizeof(Impl_::kd_));

  // @@protoc_insertion_point(copy_constructor:mc_communication_msgs_proto.MessageCommand)
}
PROTOBUF_NDEBUG_INLINE MessageCommand::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
: _cached_size_{0}, position_{visibility, arena}, velocity_{visibility, arena}, torque_{visibility, arena}
{
}

inline void MessageCommand::SharedCtor(::_pb::Arena * PROTOBUF_NULLABLE arena)
{
  new(&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) + offsetof(Impl_, kp_), 0,
           offsetof(Impl_, kd_) - offsetof(Impl_, kp_) + sizeof(Impl_::kd_));
}
MessageCommand::~MessageCommand()
{
  // @@protoc_insertion_point(destructor:mc_communication_msgs_proto.MessageCommand)
  SharedDtor(*this);
}
inline void MessageCommand::SharedDtor(MessageLite & self)
{
  MessageCommand & this_ = static_cast<MessageCommand &>(self);
  if constexpr(::_pbi::DebugHardenVerifyHasBitConsistency())
  {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void * PROTOBUF_NONNULL MessageCommand::PlacementNew_(const void * PROTOBUF_NONNULL,
                                                             void * PROTOBUF_NONNULL mem,
                                                             ::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
{
  return ::new(mem) MessageCommand(arena);
}
constexpr auto MessageCommand::InternalNewImpl_()
{
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.position_)
          + decltype(MessageCommand::_impl_.position_)::InternalGetArenaOffset(
              ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.velocity_)
          + decltype(MessageCommand::_impl_.velocity_)::InternalGetArenaOffset(
              ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.torque_)
          + decltype(MessageCommand::_impl_.torque_)::InternalGetArenaOffset(
              ::google::protobuf::Message::internal_visibility()),
  });
  if(arena_bits.has_value())
  {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MessageCommand), alignof(MessageCommand),
                                                                  *arena_bits);
  }
  else
  {
    return ::google::protobuf::internal::MessageCreator(&MessageCommand::PlacementNew_, sizeof(MessageCommand),
                                                        alignof(MessageCommand));
  }
}
constexpr auto MessageCommand::InternalGenerateClassData_()
{
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MessageCommand_default_instance_._instance,
          &_table_.header,
          nullptr, // OnDemandRegisterArenaDtor
          nullptr, // IsInitialized
          &MessageCommand::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MessageCommand>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MessageCommand::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MessageCommand>(),
          &MessageCommand::ByteSizeLong,
          &MessageCommand::_InternalSerialize,
#endif // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_._cached_size_),
          false,
      },
      &MessageCommand::kDescriptorMethods,
      &descriptor_table_mc_5frtc_5fmsgs_2eproto,
      nullptr, // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
    MessageCommand_class_data_ = MessageCommand::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData * PROTOBUF_NONNULL
    MessageCommand::GetClassData() const
{
  ::google::protobuf::internal::PrefetchToLocalCache(&MessageCommand_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MessageCommand_class_data_.tc_table);
  return MessageCommand_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<3, 5, 0, 0, 2> MessageCommand::_table_ = {
    {
        PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_._has_bits_),
        0, // no _extensions_
        5,
        56, // max_field_number, fast_idx_mask
        offsetof(decltype(_table_), field_lookup_table),
        4294967264, // skipmap
        offsetof(decltype(_table_), field_entries),
        5,                                        // num_field_entries
        0,                                        // num_aux_entries
        offsetof(decltype(_table_), field_names), // no aux_entries
        MessageCommand_class_data_.base(),
        nullptr,                           // post_loop_handler
        ::_pbi::TcParser::GenericFallback, // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
        ::_pbi::TcParser::GetTable<::mc_communication_msgs_proto::MessageCommand>(), // to_prefetch
#endif                                                                               // PROTOBUF_PREFETCH_PARSE_TABLE
    },
    {{
        {::_pbi::TcParser::MiniParse, {}},
        // double kp = 1;
        {::_pbi::TcParser::FastF64S1, {9, 0, 0, PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.kp_)}},
        // double kd = 2;
        {::_pbi::TcParser::FastF64S1, {17, 1, 0, PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.kd_)}},
        // repeated double position = 3;
        {::_pbi::TcParser::FastF64P1, {26, 63, 0, PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.position_)}},
        // repeated double velocity = 4;
        {::_pbi::TcParser::FastF64P1, {34, 63, 0, PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.velocity_)}},
        // repeated double torque = 5;
        {::_pbi::TcParser::FastF64P1, {42, 63, 0, PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.torque_)}},
        {::_pbi::TcParser::MiniParse, {}},
        {::_pbi::TcParser::MiniParse, {}},
    }},
    {{65535, 65535}},
    {{
        // double kp = 1;
        {PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.kp_), _Internal::kHasBitsOffset + 0, 0,
         (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
        // double kd = 2;
        {PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.kd_), _Internal::kHasBitsOffset + 1, 0,
         (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
        // repeated double position = 3;
        {PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.position_), -1, 0,
         (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
        // repeated double velocity = 4;
        {PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.velocity_), -1, 0,
         (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
        // repeated double torque = 5;
        {PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.torque_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    }},
    // no aux_entries
    {{}},
};
PROTOBUF_NOINLINE void MessageCommand::Clear()
{
  // @@protoc_insertion_point(message_clear_start:mc_communication_msgs_proto.MessageCommand)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  _impl_.position_.Clear();
  _impl_.velocity_.Clear();
  _impl_.torque_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if((cached_has_bits & 0x00000003U) != 0)
  {
    ::memset(&_impl_.kp_, 0,
             static_cast<::size_t>(reinterpret_cast<char *>(&_impl_.kd_) - reinterpret_cast<char *>(&_impl_.kp_))
                 + sizeof(_impl_.kd_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t * PROTOBUF_NONNULL
    MessageCommand::_InternalSerialize(const ::google::protobuf::MessageLite & base,
                                       ::uint8_t * PROTOBUF_NONNULL target,
                                       ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream)
{
  const MessageCommand & this_ = static_cast<const MessageCommand &>(base);
#else  // PROTOBUF_CUSTOM_VTABLE
::uint8_t * PROTOBUF_NONNULL
    MessageCommand::_InternalSerialize(::uint8_t * PROTOBUF_NONNULL target,
                                       ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) const
{
  const MessageCommand & this_ = *this;
#endif // PROTOBUF_CUSTOM_VTABLE
  if constexpr(::_pbi::DebugHardenVerifyHasBitConsistency())
  {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:mc_communication_msgs_proto.MessageCommand)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // double kp = 1;
  if((this_._impl_._has_bits_[0] & 0x00000001U) != 0)
  {
    if(::absl::bit_cast<::uint64_t>(this_._internal_kp()) != 0)
    {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this_._internal_kp(), target);
    }
  }

  // double kd = 2;
  if((this_._impl_._has_bits_[0] & 0x00000002U) != 0)
  {
    if(::absl::bit_cast<::uint64_t>(this_._internal_kd()) != 0)
    {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this_._internal_kd(), target);
    }
  }

  // repeated double position = 3;
  if(this_._internal_position_size() > 0)
  {
    target = stream->WriteFixedPacked(3, this_._internal_position(), target);
  }

  // repeated double velocity = 4;
  if(this_._internal_velocity_size() > 0)
  {
    target = stream->WriteFixedPacked(4, this_._internal_velocity(), target);
  }

  // repeated double torque = 5;
  if(this_._internal_torque_size() > 0)
  {
    target = stream->WriteFixedPacked(5, this_._internal_torque(), target);
  }

  if(ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields()))
  {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
            ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mc_communication_msgs_proto.MessageCommand)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MessageCommand::ByteSizeLong(const MessageLite & base)
{
  const MessageCommand & this_ = static_cast<const MessageCommand &>(base);
#else  // PROTOBUF_CUSTOM_VTABLE
::size_t MessageCommand::ByteSizeLong() const
{
  const MessageCommand & this_ = *this;
#endif // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mc_communication_msgs_proto.MessageCommand)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  {
    // repeated double position = 3;
    {
      ::size_t data_size = ::size_t{8} * ::_pbi::FromIntSize(this_._internal_position_size());
      ::size_t tag_size = data_size == 0 ? 0 : 1 + ::_pbi::WireFormatLite::Int32Size(static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double velocity = 4;
    {
      ::size_t data_size = ::size_t{8} * ::_pbi::FromIntSize(this_._internal_velocity_size());
      ::size_t tag_size = data_size == 0 ? 0 : 1 + ::_pbi::WireFormatLite::Int32Size(static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double torque = 5;
    {
      ::size_t data_size = ::size_t{8} * ::_pbi::FromIntSize(this_._internal_torque_size());
      ::size_t tag_size = data_size == 0 ? 0 : 1 + ::_pbi::WireFormatLite::Int32Size(static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if((cached_has_bits & 0x00000003U) != 0)
  {
    // double kp = 1;
    if((cached_has_bits & 0x00000001U) != 0)
    {
      if(::absl::bit_cast<::uint64_t>(this_._internal_kp()) != 0)
      {
        total_size += 9;
      }
    }
    // double kd = 2;
    if((cached_has_bits & 0x00000002U) != 0)
    {
      if(::absl::bit_cast<::uint64_t>(this_._internal_kd()) != 0)
      {
        total_size += 9;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size, &this_._impl_._cached_size_);
}

void MessageCommand::MergeImpl(::google::protobuf::MessageLite & to_msg,
                               const ::google::protobuf::MessageLite & from_msg)
{
  auto * const _this = static_cast<MessageCommand *>(&to_msg);
  auto & from = static_cast<const MessageCommand &>(from_msg);
  if constexpr(::_pbi::DebugHardenVerifyHasBitConsistency())
  {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:mc_communication_msgs_proto.MessageCommand)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  _this->_internal_mutable_position()->MergeFrom(from._internal_position());
  _this->_internal_mutable_velocity()->MergeFrom(from._internal_velocity());
  _this->_internal_mutable_torque()->MergeFrom(from._internal_torque());
  cached_has_bits = from._impl_._has_bits_[0];
  if((cached_has_bits & 0x00000003U) != 0)
  {
    if((cached_has_bits & 0x00000001U) != 0)
    {
      if(::absl::bit_cast<::uint64_t>(from._internal_kp()) != 0)
      {
        _this->_impl_.kp_ = from._impl_.kp_;
      }
    }
    if((cached_has_bits & 0x00000002U) != 0)
    {
      if(::absl::bit_cast<::uint64_t>(from._internal_kd()) != 0)
      {
        _this->_impl_.kd_ = from._impl_.kd_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MessageCommand::CopyFrom(const MessageCommand & from)
{
  // @@protoc_insertion_point(class_specific_copy_from_start:mc_communication_msgs_proto.MessageCommand)
  if(&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageCommand::InternalSwap(MessageCommand * PROTOBUF_RESTRICT PROTOBUF_NONNULL other)
{
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.position_.InternalSwap(&other->_impl_.position_);
  _impl_.velocity_.InternalSwap(&other->_impl_.velocity_);
  _impl_.torque_.InternalSwap(&other->_impl_.torque_);
  ::google::protobuf::internal::memswap<PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.kd_)
                                        + sizeof(MessageCommand::_impl_.kd_)
                                        - PROTOBUF_FIELD_OFFSET(MessageCommand, _impl_.kp_)>(
      reinterpret_cast<char *>(&_impl_.kp_), reinterpret_cast<char *>(&other->_impl_.kp_));
}

::google::protobuf::Metadata MessageCommand::GetMetadata() const
{
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MessageEnvelope::_Internal
{
public:
  using HasBits = decltype(::std::declval<MessageEnvelope>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset = 8 * PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::mc_communication_msgs_proto::MessageEnvelope, _impl_._oneof_case_);
};

void MessageEnvelope::set_allocated_config(::mc_communication_msgs_proto::MessageConfig * PROTOBUF_NULLABLE config)
{
  ::google::protobuf::Arena * message_arena = GetArena();
  clear_payload();
  if(config)
  {
    ::google::protobuf::Arena * submessage_arena = config->GetArena();
    if(message_arena != submessage_arena)
    {
      config = ::google::protobuf::internal::GetOwnedMessage(message_arena, config, submessage_arena);
    }
    set_has_config();
    _impl_.payload_.config_ = config;
  }
  // @@protoc_insertion_point(field_set_allocated:mc_communication_msgs_proto.MessageEnvelope.config)
}
void MessageEnvelope::set_allocated_state(::mc_communication_msgs_proto::MessageState * PROTOBUF_NULLABLE state)
{
  ::google::protobuf::Arena * message_arena = GetArena();
  clear_payload();
  if(state)
  {
    ::google::protobuf::Arena * submessage_arena = state->GetArena();
    if(message_arena != submessage_arena)
    {
      state = ::google::protobuf::internal::GetOwnedMessage(message_arena, state, submessage_arena);
    }
    set_has_state();
    _impl_.payload_.state_ = state;
  }
  // @@protoc_insertion_point(field_set_allocated:mc_communication_msgs_proto.MessageEnvelope.state)
}
void MessageEnvelope::set_allocated_command(::mc_communication_msgs_proto::MessageCommand * PROTOBUF_NULLABLE command)
{
  ::google::protobuf::Arena * message_arena = GetArena();
  clear_payload();
  if(command)
  {
    ::google::protobuf::Arena * submessage_arena = command->GetArena();
    if(message_arena != submessage_arena)
    {
      command = ::google::protobuf::internal::GetOwnedMessage(message_arena, command, submessage_arena);
    }
    set_has_command();
    _impl_.payload_.command_ = command;
  }
  // @@protoc_insertion_point(field_set_allocated:mc_communication_msgs_proto.MessageEnvelope.command)
}
MessageEnvelope::MessageEnvelope(::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
: ::google::protobuf::Message(arena, MessageEnvelope_class_data_.base())
{
#else  // PROTOBUF_CUSTOM_VTABLE
: ::google::protobuf::Message(arena)
{
#endif // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mc_communication_msgs_proto.MessageEnvelope)
}
PROTOBUF_NDEBUG_INLINE MessageEnvelope::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena,
    const Impl_ & from,
    [[maybe_unused]] const ::mc_communication_msgs_proto::MessageEnvelope & from_msg)
: _has_bits_{from._has_bits_}, _cached_size_{0}, topic_(arena, from.topic_), payload_{},
  _oneof_case_{from._oneof_case_[0]}
{
}

MessageEnvelope::MessageEnvelope(::google::protobuf::Arena * PROTOBUF_NULLABLE arena, const MessageEnvelope & from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
: ::google::protobuf::Message(arena, MessageEnvelope_class_data_.base())
{
#else  // PROTOBUF_CUSTOM_VTABLE
: ::google::protobuf::Message(arena)
{
#endif // PROTOBUF_CUSTOM_VTABLE
  MessageEnvelope * const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
  new(&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.timestamp_ = from._impl_.timestamp_;
  switch(payload_case())
  {
    case PAYLOAD_NOT_SET:
      break;
    case kConfig:
      _impl_.payload_.config_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.config_);
      break;
    case kState:
      _impl_.payload_.state_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.state_);
      break;
    case kCommand:
      _impl_.payload_.command_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.command_);
      break;
  }

  // @@protoc_insertion_point(copy_constructor:mc_communication_msgs_proto.MessageEnvelope)
}
PROTOBUF_NDEBUG_INLINE MessageEnvelope::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
: _cached_size_{0}, topic_(arena), payload_{}, _oneof_case_{}
{
}

inline void MessageEnvelope::SharedCtor(::_pb::Arena * PROTOBUF_NULLABLE arena)
{
  new(&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timestamp_ = {};
}
MessageEnvelope::~MessageEnvelope()
{
  // @@protoc_insertion_point(destructor:mc_communication_msgs_proto.MessageEnvelope)
  SharedDtor(*this);
}
inline void MessageEnvelope::SharedDtor(MessageLite & self)
{
  MessageEnvelope & this_ = static_cast<MessageEnvelope &>(self);
  if constexpr(::_pbi::DebugHardenVerifyHasBitConsistency())
  {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.topic_.Destroy();
  if(this_.has_payload())
  {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void MessageEnvelope::clear_payload()
{
  // @@protoc_insertion_point(one_of_clear_start:mc_communication_msgs_proto.MessageEnvelope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch(payload_case())
  {
    case kConfig:
    {
      if(GetArena() == nullptr)
      {
        delete _impl_.payload_.config_;
      }
      else if(::google::protobuf::internal::DebugHardenClearOneofMessageOnArena())
      {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.config_);
      }
      break;
    }
    case kState:
    {
      if(GetArena() == nullptr)
      {
        delete _impl_.payload_.state_;
      }
      else if(::google::protobuf::internal::DebugHardenClearOneofMessageOnArena())
      {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.state_);
      }
      break;
    }
    case kCommand:
    {
      if(GetArena() == nullptr)
      {
        delete _impl_.payload_.command_;
      }
      else if(::google::protobuf::internal::DebugHardenClearOneofMessageOnArena())
      {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.command_);
      }
      break;
    }
    case PAYLOAD_NOT_SET:
    {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}

inline void * PROTOBUF_NONNULL MessageEnvelope::PlacementNew_(const void * PROTOBUF_NONNULL,
                                                              void * PROTOBUF_NONNULL mem,
                                                              ::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
{
  return ::new(mem) MessageEnvelope(arena);
}
constexpr auto MessageEnvelope::InternalNewImpl_()
{
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MessageEnvelope), alignof(MessageEnvelope));
}
constexpr auto MessageEnvelope::InternalGenerateClassData_()
{
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MessageEnvelope_default_instance_._instance,
          &_table_.header,
          nullptr, // OnDemandRegisterArenaDtor
          nullptr, // IsInitialized
          &MessageEnvelope::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MessageEnvelope>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MessageEnvelope::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MessageEnvelope>(),
          &MessageEnvelope::ByteSizeLong,
          &MessageEnvelope::_InternalSerialize,
#endif // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_._cached_size_),
          false,
      },
      &MessageEnvelope::kDescriptorMethods,
      &descriptor_table_mc_5frtc_5fmsgs_2eproto,
      nullptr, // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
    MessageEnvelope_class_data_ = MessageEnvelope::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData * PROTOBUF_NONNULL
    MessageEnvelope::GetClassData() const
{
  ::google::protobuf::internal::PrefetchToLocalCache(&MessageEnvelope_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MessageEnvelope_class_data_.tc_table);
  return MessageEnvelope_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<1, 5, 3, 57, 2>
    MessageEnvelope::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_._has_bits_),
            0, // no _extensions_
            5,
            8, // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967264, // skipmap
            offsetof(decltype(_table_), field_entries),
            5, // num_field_entries
            3, // num_aux_entries
            offsetof(decltype(_table_), aux_entries),
            MessageEnvelope_class_data_.base(),
            nullptr,                           // post_loop_handler
            ::_pbi::TcParser::GenericFallback, // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::mc_communication_msgs_proto::MessageEnvelope>(), // to_prefetch
#endif // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // uint64 timestamp = 2;
            {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MessageEnvelope, _impl_.timestamp_), 1>(),
             {16, 1, 0, PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.timestamp_)}},
            // string topic = 1;
            {::_pbi::TcParser::FastUS1, {10, 0, 0, PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.topic_)}},
        }},
        {{65535, 65535}},
        {{
            // string topic = 1;
            {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.topic_), _Internal::kHasBitsOffset + 0, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
            // uint64 timestamp = 2;
            {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.timestamp_), _Internal::kHasBitsOffset + 1, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
            // .mc_communication_msgs_proto.MessageConfig config = 3;
            {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.payload_.config_), _Internal::kOneofCaseOffset + 0, 0,
             (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
            // .mc_communication_msgs_proto.MessageState state = 4;
            {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.payload_.state_), _Internal::kOneofCaseOffset + 0, 1,
             (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
            // .mc_communication_msgs_proto.MessageCommand command = 5;
            {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.payload_.command_), _Internal::kOneofCaseOffset + 0, 2,
             (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
        }},
        {{
            {::_pbi::TcParser::GetTable<::mc_communication_msgs_proto::MessageConfig>()},
            {::_pbi::TcParser::GetTable<::mc_communication_msgs_proto::MessageState>()},
            {::_pbi::TcParser::GetTable<::mc_communication_msgs_proto::MessageCommand>()},
        }},
        {{"\53\5\0\0\0\0\0\0"
          "mc_communication_msgs_proto.MessageEnvelope"
          "topic"}},
    };
PROTOBUF_NOINLINE void MessageEnvelope::Clear()
{
  // @@protoc_insertion_point(message_clear_start:mc_communication_msgs_proto.MessageEnvelope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if((cached_has_bits & 0x00000001U) != 0)
  {
    _impl_.topic_.ClearNonDefaultToEmpty();
  }
  _impl_.timestamp_ = ::uint64_t{0u};
  clear_payload();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t * PROTOBUF_NONNULL
    MessageEnvelope::_InternalSerialize(const ::google::protobuf::MessageLite & base,
                                        ::uint8_t * PROTOBUF_NONNULL target,
                                        ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream)
{
  const MessageEnvelope & this_ = static_cast<const MessageEnvelope &>(base);
#else  // PROTOBUF_CUSTOM_VTABLE
::uint8_t * PROTOBUF_NONNULL
    MessageEnvelope::_InternalSerialize(::uint8_t * PROTOBUF_NONNULL target,
                                        ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) const
{
  const MessageEnvelope & this_ = *this;
#endif // PROTOBUF_CUSTOM_VTABLE
  if constexpr(::_pbi::DebugHardenVerifyHasBitConsistency())
  {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:mc_communication_msgs_proto.MessageEnvelope)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string topic = 1;
  if((this_._impl_._has_bits_[0] & 0x00000001U) != 0)
  {
    if(!this_._internal_topic().empty())
    {
      const ::std::string & _s = this_._internal_topic();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "mc_communication_msgs_proto.MessageEnvelope.topic");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // uint64 timestamp = 2;
  if((this_._impl_._has_bits_[0] & 0x00000002U) != 0)
  {
    if(this_._internal_timestamp() != 0)
    {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this_._internal_timestamp(), target);
    }
  }

  switch(this_.payload_case())
  {
    case kConfig:
    {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *this_._impl_.payload_.config_, this_._impl_.payload_.config_->GetCachedSize(), target, stream);
      break;
    }
    case kState:
    {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *this_._impl_.payload_.state_, this_._impl_.payload_.state_->GetCachedSize(), target, stream);
      break;
    }
    case kCommand:
    {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          5, *this_._impl_.payload_.command_, this_._impl_.payload_.command_->GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  if(ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields()))
  {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
            ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mc_communication_msgs_proto.MessageEnvelope)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MessageEnvelope::ByteSizeLong(const MessageLite & base)
{
  const MessageEnvelope & this_ = static_cast<const MessageEnvelope &>(base);
#else  // PROTOBUF_CUSTOM_VTABLE
::size_t MessageEnvelope::ByteSizeLong() const
{
  const MessageEnvelope & this_ = *this;
#endif // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mc_communication_msgs_proto.MessageEnvelope)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if((cached_has_bits & 0x00000003U) != 0)
  {
    // string topic = 1;
    if((cached_has_bits & 0x00000001U) != 0)
    {
      if(!this_._internal_topic().empty())
      {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(this_._internal_topic());
      }
    }
    // uint64 timestamp = 2;
    if((cached_has_bits & 0x00000002U) != 0)
    {
      if(this_._internal_timestamp() != 0)
      {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this_._internal_timestamp());
      }
    }
  }
  switch(this_.payload_case())
  {
    // .mc_communication_msgs_proto.MessageConfig config = 3;
    case kConfig:
    {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.config_);
      break;
    }
    // .mc_communication_msgs_proto.MessageState state = 4;
    case kState:
    {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.state_);
      break;
    }
    // .mc_communication_msgs_proto.MessageCommand command = 5;
    case kCommand:
    {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.command_);
      break;
    }
    case PAYLOAD_NOT_SET:
    {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size, &this_._impl_._cached_size_);
}

void MessageEnvelope::MergeImpl(::google::protobuf::MessageLite & to_msg,
                                const ::google::protobuf::MessageLite & from_msg)
{
  auto * const _this = static_cast<MessageEnvelope *>(&to_msg);
  auto & from = static_cast<const MessageEnvelope &>(from_msg);
  if constexpr(::_pbi::DebugHardenVerifyHasBitConsistency())
  {
    from.VerifyHasBitConsistency();
  }
  ::google::protobuf::Arena * arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:mc_communication_msgs_proto.MessageEnvelope)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if((cached_has_bits & 0x00000003U) != 0)
  {
    if((cached_has_bits & 0x00000001U) != 0)
    {
      if(!from._internal_topic().empty())
      {
        _this->_internal_set_topic(from._internal_topic());
      }
      else
      {
        if(_this->_impl_.topic_.IsDefault())
        {
          _this->_internal_set_topic("");
        }
      }
    }
    if((cached_has_bits & 0x00000002U) != 0)
    {
      if(from._internal_timestamp() != 0)
      {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if(const uint32_t oneof_from_case = from._impl_._oneof_case_[0])
  {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if(oneof_needs_init)
    {
      if(oneof_to_case != 0)
      {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch(oneof_from_case)
    {
      case kConfig:
      {
        if(oneof_needs_init)
        {
          _this->_impl_.payload_.config_ =
              ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.config_);
        }
        else
        {
          _this->_impl_.payload_.config_->MergeFrom(*from._impl_.payload_.config_);
        }
        break;
      }
      case kState:
      {
        if(oneof_needs_init)
        {
          _this->_impl_.payload_.state_ =
              ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.state_);
        }
        else
        {
          _this->_impl_.payload_.state_->MergeFrom(*from._impl_.payload_.state_);
        }
        break;
      }
      case kCommand:
      {
        if(oneof_needs_init)
        {
          _this->_impl_.payload_.command_ =
              ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.command_);
        }
        else
        {
          _this->_impl_.payload_.command_->MergeFrom(*from._impl_.payload_.command_);
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MessageEnvelope::CopyFrom(const MessageEnvelope & from)
{
  // @@protoc_insertion_point(class_specific_copy_from_start:mc_communication_msgs_proto.MessageEnvelope)
  if(&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageEnvelope::InternalSwap(MessageEnvelope * PROTOBUF_RESTRICT PROTOBUF_NONNULL other)
{
  using ::std::swap;
  auto * arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.topic_, &other->_impl_.topic_, arena);
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata MessageEnvelope::GetMetadata() const
{
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
} // namespace mc_communication_msgs_proto
namespace google
{
namespace protobuf
{
} // namespace protobuf
} // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type _static_init2_ [[maybe_unused]] =
    (::_pbi::AddDescriptors(&descriptor_table_mc_5frtc_5fmsgs_2eproto), ::std::false_type{});
#include "google/protobuf/port_undef.inc"
