find_package(GTest REQUIRED)
include(GoogleTest)

set(TEST_CONFIG_DIR "${CMAKE_CURRENT_SOURCE_DIR}/etc")

configure_file(
  ${CMAKE_CURRENT_SOURCE_DIR}/config.in.h ${CMAKE_CURRENT_BINARY_DIR}/config.h
  @ONLY
)

function(add_mc_test TEST_NAME)
  add_executable(${TEST_NAME} ${ARGN})

  target_link_libraries(${TEST_NAME} PRIVATE robot_comm GTest::gtest_main)

  target_include_directories(
    ${TEST_NAME} PRIVATE $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>
  )

  gtest_discover_tests(${TEST_NAME})
endfunction()

add_mc_test(test_config test_config.cpp)
add_mc_test(test_server test_server.cpp)
add_mc_test(test_multiple test_multiple.cpp)
# add_mc_test(test_shm test_shm.cpp)
